% =============================================================================
% TIER 3 module: STRUCTURAL INDUCTION OVER `path`, AT ONE PREDICATE.
%
% THE ONE TRUSTED ITEM IN THIS TIER, and it is a STANDARD PRINCIPLE rather than
% a domain fact.  `path` is the free term algebra generated by `nil` and
% `cons : item * path > path` (its freeness axioms are in `_paths.p`:
% `cons_not_nil`, `cons_inj`, `path_cases`).  For such an algebra the induction
% schema
%
%     Phi(nil)  and  ForAll H,T. (Phi(T) => Phi(cons(H,T)))   =>   ForAll P. Phi(P)
%
% is valid.  It is a SCHEMA — it quantifies over the formula Phi — so plain
% first-order logic cannot state it, and saturation-based provers have no
% induction rule to derive it.  This file therefore states the ONE INSTANCE the
% corpus needs, with Phi(P) := "app(P, -) is injective".
%
% WHY THIS IS DIFFERENT FROM ADMITTING THE CONCLUSION.  `_cancel.p` used to
% assert the conclusion itself, `app(P,Q) = app(P,R) => Q = R`, as an axiom —
% i.e. the whole fact, about `app`, taken on trust, with `wrap_roundtrip.p` and
% `card_wrap.p` proved relative to it.  What is trusted HERE mentions `app` only
% inside the schema's two premises, and says nothing whatever about what `app`
% computes: instantiate Phi with any other property of paths and the axiom is
% just as true.  The two premises remain OBLIGATIONS:
%
%     Phi(nil)                        proofs/unbounded/mon_cancel_base.p   PROVED
%     ForAll H,T. Phi(T)=>Phi(cons)   proofs/unbounded/mon_cancel_step.p   PROVED
%
% and vampire has to re-derive both from `_paths.p` before it can use this
% implication — `mon_cancel.p` is closed in 0.02 s in DEFAULT mode, which is a
% measure of how little is left to do once the schema instance is available.
% This is the same discipline `terminating/fixpoint_is_lfp.smt2` uses for its
% four inductions: base and step machine-checked, then the bridging principle
% asserted exactly as a hand proof invokes it.
%
% MEASURED 2026-09-02, vampire 5.1.0 (commit 7b2f410).  Before this file existed
% the direct attempt at the conclusion was OPEN at a 180 s portfolio budget, and
% so were `--induction struct` / `--induction int` and an SMT-LIB2 rendering with
% `declare-datatypes` (which z3 also could not close at 50 s) — the attempt log
% is in `mon_cancel.p`.
%
% WHY THE PREDICATE IS INLINED.  A first attempt introduced `cancels : path > $o`
% with a defining equivalence and stated the schema over it.  MEASURED: vampire
% could not close `mon_cancel.p` at a 150 s portfolio budget that way — the
% `<=>` with two nested universal quantifiers on the right generates both
% directions at every instantiation.  Writing the two premises out in full
% closes it in 0.02 s.
% =============================================================================

tff(path_induction_cancel, axiom,
    ( (   ( ! [Q: path, R: path] : ( app(nil,Q) = app(nil,R) => Q = R ) )
        & ( ! [H: item, T: path] :
              ( ( ! [Q: path, R: path] : ( app(T,Q) = app(T,R) => Q = R ) )
             => ( ! [Q: path, R: path] :
                    ( app(cons(H,T),Q) = app(cons(H,T),R) => Q = R ) ) ) ) )
   => ( ! [P: path, Q: path, R: path] : ( app(P,Q) = app(P,R) => Q = R ) ) ) ).
