% Generated by morkl.CornerstoneProofArtifactMain
% 15-puzzle:space_optimized
% Default source optimizer output equals original Space/term output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s31352d70757a7a6c655f73706163655f6f7074696d697a65645f6c6873) <=> (P = cons(s52304331,cons(s31,cons(s32,cons(s33,cons(s34,cons(s35,cons(s36,cons(s37,cons(s38,cons(s39,cons(s3130,cons(s3131,cons(s3132,cons(s3133,cons(s3134,cons(s3135,nil)))))))))))))))) | P = cons(s52314330,cons(s34,cons(s31,cons(s32,cons(s33,cons(s35,cons(s36,cons(s37,cons(s38,cons(s39,cons(s3130,cons(s3131,cons(s3132,cons(s3133,cons(s3134,cons(s3135,nil))))))))))))))))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s31352d70757a7a6c655f73706163655f6f7074696d697a65645f726873) <=> (P = cons(s52304331,cons(s31,cons(s32,cons(s33,cons(s34,cons(s35,cons(s36,cons(s37,cons(s38,cons(s39,cons(s3130,cons(s3131,cons(s3132,cons(s3133,cons(s3134,cons(s3135,nil)))))))))))))))) | P = cons(s52314330,cons(s34,cons(s31,cons(s32,cons(s33,cons(s35,cons(s36,cons(s37,cons(s38,cons(s39,cons(s3130,cons(s3131,cons(s3132,cons(s3133,cons(s3134,cons(s3135,nil))))))))))))))))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s31352d70757a7a6c655f73706163655f6f7074696d697a65645f6c6873) <=> p_mem(P,s31352d70757a7a6c655f73706163655f6f7074696d697a65645f726873))).
