% Generated by morkl.CornerstoneProofArtifactMain
% aunt:zipper_vs_space
% Scala zipper program materialization equals eager Space/Trie evaluation.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s61756e745f7a69707065725f76735f73706163655f6c6873) <=> (P = cons(s41756e74,cons(s416e6e,cons(s4c697a,nil))) | P = cons(s41756e74,cons(s4a696d,cons(s416e6e,nil))) | P = cons(s41756e74,cons(s506174,cons(s4c697a,nil)))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s61756e745f7a69707065725f76735f73706163655f726873) <=> (P = cons(s41756e74,cons(s416e6e,cons(s4c697a,nil))) | P = cons(s41756e74,cons(s4a696d,cons(s416e6e,nil))) | P = cons(s41756e74,cons(s506174,cons(s4c697a,nil)))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s61756e745f7a69707065725f76735f73706163655f6c6873) <=> p_mem(P,s61756e745f7a69707065725f76735f73706163655f726873))).
