% Generated by morkl.CornerstoneProofArtifactMain
% aunt:space_optimized
% Default source optimizer output equals original Space/term output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s61756e745f73706163655f6f7074696d697a65645f6c6873) <=> (P = cons(s41756e74,cons(s416e6e,cons(s4c697a,nil))) | P = cons(s41756e74,cons(s4a696d,cons(s416e6e,nil))) | P = cons(s41756e74,cons(s506174,cons(s4c697a,nil)))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s61756e745f73706163655f6f7074696d697a65645f726873) <=> (P = cons(s41756e74,cons(s416e6e,cons(s4c697a,nil))) | P = cons(s41756e74,cons(s4a696d,cons(s416e6e,nil))) | P = cons(s41756e74,cons(s506174,cons(s4c697a,nil)))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s61756e745f73706163655f6f7074696d697a65645f6c6873) <=> p_mem(P,s61756e745f73706163655f6f7074696d697a65645f726873))).
