% Generated by morkl.CornerstoneProofArtifactMain
% aunt:trie_vs_reference
% Trie evaluator output equals reference set evaluator output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s61756e745f747269655f76735f7265666572656e63655f6c6873) <=> (P = cons(s41756e74,cons(s416e6e,cons(s4c697a,nil))) | P = cons(s41756e74,cons(s4a696d,cons(s416e6e,nil))) | P = cons(s41756e74,cons(s506174,cons(s4c697a,nil)))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s61756e745f747269655f76735f7265666572656e63655f726873) <=> (P = cons(s41756e74,cons(s416e6e,cons(s4c697a,nil))) | P = cons(s41756e74,cons(s4a696d,cons(s416e6e,nil))) | P = cons(s41756e74,cons(s506174,cons(s4c697a,nil)))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s61756e745f747269655f76735f7265666572656e63655f6c6873) <=> p_mem(P,s61756e745f747269655f76735f7265666572656e63655f726873))).
