% Generated by morkl.CornerstoneProofArtifactMain
% gol:zipper_vs_space
% Scala zipper program materialization equals eager Space/Trie evaluation.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s676f6c5f7a69707065725f76735f73706163655f6c6873) <=> (P = cons(s43656c6c,cons(s30,cons(s30,nil))) | P = cons(s43656c6c,cons(s30,cons(s31,nil))) | P = cons(s43656c6c,cons(s31,cons(s30,nil))) | P = cons(s43656c6c,cons(s31,cons(s31,nil)))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s676f6c5f7a69707065725f76735f73706163655f726873) <=> (P = cons(s43656c6c,cons(s30,cons(s30,nil))) | P = cons(s43656c6c,cons(s30,cons(s31,nil))) | P = cons(s43656c6c,cons(s31,cons(s30,nil))) | P = cons(s43656c6c,cons(s31,cons(s31,nil)))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s676f6c5f7a69707065725f76735f73706163655f6c6873) <=> p_mem(P,s676f6c5f7a69707065725f76735f73706163655f726873))).
