% Generated by morkl.CornerstoneProofArtifactMain
% gol:trie_vs_reference
% Trie evaluator output equals reference set evaluator output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s676f6c5f747269655f76735f7265666572656e63655f6c6873) <=> (P = cons(s43656c6c,cons(s30,cons(s30,nil))) | P = cons(s43656c6c,cons(s30,cons(s31,nil))) | P = cons(s43656c6c,cons(s31,cons(s30,nil))) | P = cons(s43656c6c,cons(s31,cons(s31,nil)))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s676f6c5f747269655f76735f7265666572656e63655f726873) <=> (P = cons(s43656c6c,cons(s30,cons(s30,nil))) | P = cons(s43656c6c,cons(s30,cons(s31,nil))) | P = cons(s43656c6c,cons(s31,cons(s30,nil))) | P = cons(s43656c6c,cons(s31,cons(s31,nil)))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s676f6c5f747269655f76735f7265666572656e63655f6c6873) <=> p_mem(P,s676f6c5f747269655f76735f7265666572656e63655f726873))).
