% Generated by morkl.CornerstoneProofArtifactMain
% gol:space_optimized
% Default source optimizer output equals original Space/term output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s676f6c5f73706163655f6f7074696d697a65645f6c6873) <=> (P = cons(s43656c6c,cons(s30,cons(s30,nil))) | P = cons(s43656c6c,cons(s30,cons(s31,nil))) | P = cons(s43656c6c,cons(s31,cons(s30,nil))) | P = cons(s43656c6c,cons(s31,cons(s31,nil)))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s676f6c5f73706163655f6f7074696d697a65645f726873) <=> (P = cons(s43656c6c,cons(s30,cons(s30,nil))) | P = cons(s43656c6c,cons(s30,cons(s31,nil))) | P = cons(s43656c6c,cons(s31,cons(s30,nil))) | P = cons(s43656c6c,cons(s31,cons(s31,nil)))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s676f6c5f73706163655f6f7074696d697a65645f6c6873) <=> p_mem(P,s676f6c5f73706163655f6f7074696d697a65645f726873))).
