% Generated by morkl.CornerstoneProofArtifactMain
% nqueens:graph_execT_vs_space
% Scala operation graph execT output equals eager Space/Trie evaluation.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s6e717565656e735f67726170685f65786563545f76735f73706163655f6c6873) <=> (P = cons(s32,cons(s34,cons(s31,cons(s33,nil)))) | P = cons(s33,cons(s31,cons(s34,cons(s32,nil))))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s6e717565656e735f67726170685f65786563545f76735f73706163655f726873) <=> (P = cons(s32,cons(s34,cons(s31,cons(s33,nil)))) | P = cons(s33,cons(s31,cons(s34,cons(s32,nil))))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s6e717565656e735f67726170685f65786563545f76735f73706163655f6c6873) <=> p_mem(P,s6e717565656e735f67726170685f65786563545f76735f73706163655f726873))).
