% Generated by morkl.CornerstoneProofArtifactMain
% nqueens:space_optimized
% Default source optimizer output equals original Space/term output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s6e717565656e735f73706163655f6f7074696d697a65645f6c6873) <=> (P = cons(s32,cons(s34,cons(s31,cons(s33,nil)))) | P = cons(s33,cons(s31,cons(s34,cons(s32,nil))))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s6e717565656e735f73706163655f6f7074696d697a65645f726873) <=> (P = cons(s32,cons(s34,cons(s31,cons(s33,nil)))) | P = cons(s33,cons(s31,cons(s34,cons(s32,nil))))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s6e717565656e735f73706163655f6f7074696d697a65645f6c6873) <=> p_mem(P,s6e717565656e735f73706163655f6f7074696d697a65645f726873))).
