% Generated by morkl.CornerstoneProofArtifactMain
% nqueens:trie_vs_reference
% Trie evaluator output equals reference set evaluator output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s6e717565656e735f747269655f76735f7265666572656e63655f6c6873) <=> (P = cons(s32,cons(s34,cons(s31,cons(s33,nil)))) | P = cons(s33,cons(s31,cons(s34,cons(s32,nil))))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s6e717565656e735f747269655f76735f7265666572656e63655f726873) <=> (P = cons(s32,cons(s34,cons(s31,cons(s33,nil)))) | P = cons(s33,cons(s31,cons(s34,cons(s32,nil))))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s6e717565656e735f747269655f76735f7265666572656e63655f6c6873) <=> p_mem(P,s6e717565656e735f747269655f76735f7265666572656e63655f726873))).
