% Generated by morkl.CornerstoneProofArtifactMain
% temperature:zipper_vs_space
% Scala zipper program materialization equals eager Space/Trie evaluation.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s74656d70657261747572655f7a69707065725f76735f73706163655f6c6873) <=> (P = cons(s63656c6c,cons(s30,cons(s30,cons(s43,nil))))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s74656d70657261747572655f7a69707065725f76735f73706163655f726873) <=> (P = cons(s63656c6c,cons(s30,cons(s30,cons(s43,nil))))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s74656d70657261747572655f7a69707065725f76735f73706163655f6c6873) <=> p_mem(P,s74656d70657261747572655f7a69707065725f76735f73706163655f726873))).
