% Generated by morkl.CornerstoneProofArtifactMain
% temperature:trie_vs_reference
% Trie evaluator output equals reference set evaluator output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s74656d70657261747572655f747269655f76735f7265666572656e63655f6c6873) <=> (P = cons(s63656c6c,cons(s30,cons(s30,cons(s43,nil))))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s74656d70657261747572655f747269655f76735f7265666572656e63655f726873) <=> (P = cons(s63656c6c,cons(s30,cons(s30,cons(s43,nil))))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s74656d70657261747572655f747269655f76735f7265666572656e63655f6c6873) <=> p_mem(P,s74656d70657261747572655f747269655f76735f7265666572656e63655f726873))).
