% Generated by morkl.CornerstoneProofArtifactMain
% temperature:space_optimized
% Default source optimizer output equals original Space/term output.

fof(lhs_complete, axiom, ! [P] : (p_mem(P,s74656d70657261747572655f73706163655f6f7074696d697a65645f6c6873) <=> (P = cons(s63656c6c,cons(s30,cons(s30,cons(s43,nil))))))).
fof(rhs_complete, axiom, ! [P] : (p_mem(P,s74656d70657261747572655f73706163655f6f7074696d697a65645f726873) <=> (P = cons(s63656c6c,cons(s30,cons(s30,cons(s43,nil))))))).

fof(conj, conjecture, ! [P] : (p_mem(P,s74656d70657261747572655f73706163655f6f7074696d697a65645f6c6873) <=> p_mem(P,s74656d70657261747572655f73706163655f6f7074696d697a65645f726873))).
