#!/usr/bin/env python3
"""EVERY FILE REFERENCE IN THE TREE MUST RESOLVE.

Two failure modes this catches, both of which the repository had:

  1. a MARKDOWN LINK whose target does not exist (`[BENCHMARKS.md](BENCHMARKS.md)` after the file
     moved to `docs/`);
  2. a PROSE/COMMENT citation of a file that does not exist -- the repository had accumulated 369
     citations of an external review document that was never in the tree, spread over 42 source,
     doc, proof and script files, so a reader had no way to tell a live pointer from a dead one.
     (They are gone; the substance each one carried is stated in place.)

A reference resolves if it is found relative to the repo root, to the citing file's own directory,
or to one of the SEARCH_ROOTS (so `MORKL.scala` in a doc, or `laws/law_union_idem.smt2` in a proof header,
both resolve without spelling the full path).

Run: python3 scripts/check_references.py        # exit 1 on any dangling reference
"""
import os
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Directories a bare filename may be relative to.  Order is irrelevant: any hit resolves.
SEARCH_ROOTS = [
    "", "docs", "scripts", "proofs", "proofs/laws", "proofs/spatial", "proofs/spatial-semantic",
    "proofs/pipeline", "src/main/scala", "src/test/scala", "src/test/resources", "terminating",
    "zipper-egg-tests", "zipper-egg-tests/generated", "zipper-egg-tests/pipeline",
]

# Extensions that make a token a file reference.  `.sh` and `.p` are only honoured when the token
# also contains a `/`: bare `a.sh` is overwhelmingly a Scala field access (`a.show` abbreviated to
# `.sh`), and bare `x.p` is a variable.
ALWAYS = (".md", ".scala", ".py", ".egg", ".smt2", ".tsv", ".csv", ".png", ".sbt", ".ser", ".rle")
PATH_ONLY = (".sh", ".p", ".txt", ".json", ".jsonl")

# EXTERNAL DATASETS.  Not in the tree by design: the suites resolve them through `Loaders.resolve`
# (a `-D` override, then $ZIPPY_DATA, then a repo-relative path) and fall back to a deterministic
# inline fixture, so a fresh checkout runs green without them.
EXTERNAL_DATA = {"lot.metta", "fred.rle", "royal92_simple.metta", "noaa_slice.txt",
                 "NOAAGlobalTemp.nc"}

# Files that are GENERATED by a test/script and therefore legitimately absent from a fresh
# checkout.  Each entry names the generator, which is what a reader actually needs.
GENERATED = {
    "corpus_1000.ser": "morkl.ProgramExpressivity",
    "corpus_1000.txt": "morkl.ProgramExpressivity",
    "corpus_runtimes.csv": "morkl.CorpusRuntimes",
    "expressivity.csv": "morkl.ProgramExpressivity",
    "prog_matrix.tsv": "morkl.ProgramStats",
    "datalog-morkl.txt": "morkl.DatalogShowTest",
}

# Tokens that look like a path but are not: interpolated names, doc placeholders, scratch paths.
IGNORE_RE = re.compile(
    r"""(
      ^\$          |   # shell/egg interpolation
      \$\{         |   # scala interpolation inside the token
      ^-           |   # a SUFFIX pattern, e.g. -impl.egg / -zipper.egg / -space.egg
      ^/tmp/       |
      ^\.\.\.      |
      ^TMP/        |   # $TMP/... in check_locality.sh, written at run time
      ^[a-z]\.egg$ |   # chain$d.egg style, built by a loop
      ^name\.egg$  |
      ^stage-      |
      ^generated/rand-   # regenerated by scripts/gen_bridge_tests.py
    )""",
    re.X,
)

SKIP_FILES = {"build.log", "laws.diff", "corpus_1000.txt", "corpus_1000.ser", "expressivity.csv",
              "corpus_runtimes.csv", "MINED.tsv"}
SKIP_DIRS = {".git", ".tools", "target", ".bsp", ".idea", ".scala-build", ".bloop"}

SCAN_EXT = {".md", ".scala", ".py", ".sh", ".egg", ".smt2", ".tsv", ".sbt", ".p"}

# `(?<![\w./$-])` also rules out `$name-space.egg` / `"$1.smt2"`: a token whose first character is
# preceded by `$` is an interpolation, and the file it names exists only at run time.
TOKEN_RE = re.compile(r"(?<![\w./$-])((?:[\w.@-]+/)*[\w.@-]+\.[A-Za-z0-9]+)(?![\w])")
MDLINK_RE = re.compile(r"\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")


def resolves(ref: str, origin: pathlib.Path) -> bool:
    base = ref.split("/")[-1]
    if base in GENERATED or base in EXTERNAL_DATA:
        return True
    if (origin.parent / ref).exists():
        return True
    return any((ROOT / r / ref).exists() for r in SEARCH_ROOTS)


def scan():
    problems = []
    for f in sorted(ROOT.rglob("*")):
        if not f.is_file():
            continue
        if any(part in SKIP_DIRS for part in f.relative_to(ROOT).parts):
            continue
        if f.name in SKIP_FILES or f.suffix not in SCAN_EXT:
            continue
        try:
            text = f.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        rel = f.relative_to(ROOT)

        # (1) markdown links
        if f.suffix == ".md":
            for m in MDLINK_RE.finditer(text):
                tgt = m.group(2).split("#")[0]
                if not tgt or tgt.startswith(("http://", "https://", "mailto:")):
                    continue
                if not (f.parent / tgt).exists() and not (ROOT / tgt).exists():
                    line = text[: m.start()].count("\n") + 1
                    problems.append(f"{rel}:{line}: broken markdown link [{m.group(1)}]({m.group(2)})")

        # (2) prose / comment citations
        seen = {}
        for m in TOKEN_RE.finditer(text):
            ref = m.group(1)
            ext = "." + ref.rsplit(".", 1)[1]
            if ext in PATH_ONLY and "/" not in ref:
                continue
            if ext not in ALWAYS and ext not in PATH_ONLY:
                continue
            if IGNORE_RE.search(ref):
                continue
            if resolves(ref, f):
                continue
            line = text[: m.start()].count("\n") + 1
            seen.setdefault(ref, []).append(line)
        for ref, lines in sorted(seen.items()):
            where = ",".join(str(x) for x in lines[:4]) + ("..." if len(lines) > 4 else "")
            problems.append(f"{rel}:{where}: reference to a file that does not exist: {ref} "
                            f"({len(lines)} occurrence(s))")
    return problems


if __name__ == "__main__":
    ps = scan()
    for p in ps:
        print(p)
    print()
    print(f"dangling references: {len(ps)}")
    sys.exit(1 if ps else 0)
