#!/usr/bin/env python3
"""Generate the SPATIAL-SEMANTIC obligation corpus under proofs/spatial-semantic/ + its REGISTRY.

the review: `proofs/spatial/` contains lattice algebra and path lemmas but NOTHING that
states, let alone proves, the semantic laws

    eval(s, concreteEnv) ∈ γ(infer(s, abstractEnv))
    γ(a op# b) ⊇ γ(a) op γ(b)
    specialize(s, facts) ≡ s under facts

This corpus is the finite-first-order fragment of that family.  It is DISJOINT from
`proofs/spatial/`: nothing here re-proves an interval lattice law, and nothing there mentions γ of
the actual carrier.  The executable half lives in `src/test/scala/SpatialLawCheck.scala`; the
carrier, γ, α and the order live in `src/main/scala/SpatialGamma.scala`.

CONVENTION (same as the rest of the repo): every file asserts the NEGATION of its theorem, so
  z3 "unsat" = PROVED        z3 "sat" = COUNTERMODEL (the stated theorem is FALSE)
Every obligation is QUANTIFIER-FREE: the negated theorem is `premises ∧ ¬conclusion` over free
(skolem) constants, which is why they all discharge in well under a second.  A file whose theorem is
itself existential ("this rule IS unsound", "`within` is NOT γ-containment") states a GROUND fact
about named witness constants, so its negation is ground too.

THREE MODELS, all finite and all stated in full inside each file:

  IVL/TY  the length-indexed count carrier.  Counts are ℕ∪{∞} with ∞ a datatype constructor (the
          CODE uses a `Long.MaxValue` sentinel — that gap is not covered here and is not covered
          anywhere else either).  A `Ty` is the SpatialTypes representation restricted to a window:
          classes 0 and 1 TRACKED, lengths 2 and 3 in the SPILL bucket with a length window.  γ(Ty)
          is `SpatialGamma.gammaSpace` on that window, aggregate constraint included — which is the
          part `proofs/spatial/sp_gamma_order.smt2` (one integer in one interval) does not reach.

  L1      a depth-1 abstract trie: head universe {0,1,2}, each head's tail-set is ∅ or {ε}.  Carries
          the ε channel (3-valued), the tracked-head set, the untracked-head COUNT interval, and the
          per-head `otherTail` summary — the four channels of `SpatialGamma.gammaShape`.  Used for
          the restriction head-set rule and the head-count rules.

  L2      a depth-2 abstract trie: head universe {0,1,2}, grandchild universe {x}.  The concrete
          space is a subset of the 7 paths {ε, 0, 1, 2, 0.x, 1.x, 2.x}, so ∪ / ∩ / ∖ / tails are
          EXACT on the cells and the transfers can be certified rather than approximated.  Counts
          are plain Ints; with only 3 heads, `others.hi ≥ 3` is ⊤, which is how ∞ is modelled.

WHAT IS ASSUMED (declared, not derived):
  - `gsem_join_union_sound.smt2` asserts the three finite-measure facts about a per-length count of
    a set union (`max ≤ |A∪B| ≤ |A|+|B|`, non-negativity) as AXIOMS, marked DEFINITIONAL in the
    registry, exactly as `proofs/spatial/sp_class_bounds.smt2` does for its bridge.  Everything else
    in that file is proved on top.
  - the models above are hand-written transcriptions of the Scala.  No mechanical link ties a
    `define-fun` here to a method in `SpatialShape.scala`; the executable simulation matrix in
    `SpatialLawCheck` is what covers the actual code.
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
outdir = root / "proofs" / "spatial-semantic"
outdir.mkdir(parents=True, exist_ok=True)

HDR = "; SPATIAL-SEMANTIC OBLIGATION — {title}\n; {note}\n; Generated by scripts/gen_spatial_semantic_obligations.py.  Asserts the NEGATED theorem:\n;   z3 unsat = PROVED, z3 sat = COUNTERMODEL.  Verdicts in proofs/spatial-semantic/STATUS.tsv.\n"

# ---------------------------------------------------------------------------- preludes
CNT = """
; ── ℕ∪{∞}: ∞ is a datatype constructor, so the modelled count domain is complete.  The CODE uses
;    Ivl.INF = Long.MaxValue, a sentinel; that difference is NOT modelled here.
(declare-datatypes ((Cnt 0)) (((fin (v Int)) (oo))))
(define-fun okc ((a Cnt)) Bool (or (= a oo) (>= (v a) 0)))
(define-fun cle ((a Cnt) (b Cnt)) Bool (ite (= b oo) true (ite (= a oo) false (<= (v a) (v b)))))
(define-fun cmin ((a Cnt) (b Cnt)) Cnt (ite (cle a b) a b))
(define-fun cmax ((a Cnt) (b Cnt)) Cnt (ite (cle a b) b a))
(define-fun cadd ((a Cnt) (b Cnt)) Cnt (ite (or (= a oo) (= b oo)) oo (fin (+ (v a) (v b)))))
(declare-datatypes ((Ivl 0)) (((mki (lo Cnt) (hi Cnt)))))
(define-fun oki ((i Ivl)) Bool (and (okc (lo i)) (okc (hi i))))
; ⊑ on intervals is INCLUSION on both endpoints
(define-fun ile ((a Ivl) (b Ivl)) Bool (and (cle (lo b) (lo a)) (cle (hi a) (hi b))))
(define-fun ijoin ((a Ivl) (b Ivl)) Ivl (mki (cmin (lo a) (lo b)) (cmax (hi a) (hi b))))
; γ of ONE class interval: which concrete counts it admits
(define-fun inI ((c Int) (i Ivl)) Bool (and (>= c 0) (cle (lo i) (fin c)) (cle (fin c) (hi i))))
; the CODE's per-class UNION transfer (SpatialTypes.join): lo = max, hi = saturating +
(define-fun ucls ((a Ivl) (b Ivl)) Ivl (mki (cmax (lo a) (lo b)) (cadd (hi a) (hi b))))
"""

TY = """
; ── the length-indexed count type on a WINDOW.  Classes 0 and 1 are TRACKED; lengths 2 and 3 are
;    covered by the single SPILL bucket `rst` whose length window is [rlo, rhi].  This is
;    SpaceType's representation and `SpatialGamma.gammaSpace` its γ — note the AGGREGATE constraint
;    on the spill, which is what a one-interval model cannot express.
(declare-datatypes ((Ty 0)) (((mkty (c0 Ivl) (c1 Ivl) (rst Ivl) (rlo Int) (rhi Int)))))
(define-fun okt ((t Ty)) Bool (and (oki (c0 t)) (oki (c1 t)) (oki (rst t)) (>= (rlo t) 0) (>= (rhi t) 0)))
; a concrete space, as its per-length counts.  n0 ≤ 1 because ε is the ONLY length-0 path.
(define-fun okv ((n0 Int) (n1 Int) (n2 Int) (n3 Int)) Bool
  (and (>= n0 0) (<= n0 1) (>= n1 0) (>= n2 0) (>= n3 0)))
(define-fun inG ((t Ty) (n0 Int) (n1 Int) (n2 Int) (n3 Int)) Bool
  (and (inI n0 (c0 t)) (inI n1 (c1 t))
       (inI (+ n2 n3) (rst t))
       (=> (> n2 0) (and (<= (rlo t) 2) (<= 2 (rhi t))))
       (=> (> n3 0) (and (<= (rlo t) 3) (<= 3 (rhi t))))))
; the order that IS γ-containment (SpatialGamma.leq specialised to this window).  Note the Scala
; `leqSpace` is STRICTLY MORE CONSERVATIVE (with equal tracked sets it additionally demands
; b.rest.lo = 0), so `leqSpace ⇒ leqt`, and a theorem about leqt covers it.
(define-fun leqt ((a Ty) (b Ty)) Bool
  (and (ile (c0 a) (c0 b)) (ile (c1 a) (c1 b)) (ile (rst a) (rst b))
       (or (= (hi (rst a)) (fin 0))
           (and (<= (rlo b) (rlo a)) (<= (rhi a) (rhi b))))))
; the CODE's `SpaceType.within` — UPPER ENVELOPES ONLY, every lower bound ignored
(define-fun withint ((a Ty) (b Ty)) Bool
  (and (cle (hi (c0 a)) (hi (c0 b))) (cle (hi (c1 a)) (hi (c1 b))) (cle (hi (rst a)) (hi (rst b)))
       (or (= (hi (rst a)) (fin 0))
           (and (<= (rlo b) (rlo a)) (<= (rhi a) (rhi b))))))
; the LATTICE join (SpatialGamma.lubSpace, closed case): class-wise hull + window hull
(define-fun lubt ((a Ty) (b Ty)) Ty
  (mkty (ijoin (c0 a) (c0 b)) (ijoin (c1 a) (c1 b)) (ijoin (rst a) (rst b))
        (ite (<= (rlo a) (rlo b)) (rlo a) (rlo b)) (ite (<= (rhi a) (rhi b)) (rhi b) (rhi a))))
; the CODE's `SpatialTypes.join` — the UNION transfer, applied class-wise
(define-fun jointy ((a Ty) (b Ty)) Ty
  (mkty (ucls (c0 a) (c0 b)) (ucls (c1 a) (c1 b)) (ucls (rst a) (rst b))
        (ite (<= (rlo a) (rlo b)) (rlo a) (rlo b)) (ite (<= (rhi a) (rhi b)) (rhi b) (rhi a))))
"""

PR = """
; ── the ε channel: Presence, and its γ.  `inP p b` = "the 3-valued claim p is true of the fact b".
(declare-datatypes ((Pr 0)) (((pno) (pmay) (pmust))))
(define-fun por ((a Pr) (b Pr)) Pr
  (ite (or (= a pmust) (= b pmust)) pmust (ite (or (= a pmay) (= b pmay)) pmay pno)))
(define-fun pand ((a Pr) (b Pr)) Pr
  (ite (or (= a pno) (= b pno)) pno (ite (and (= a pmust) (= b pmust)) pmust pmay)))
(define-fun pminus ((a Pr) (b Pr)) Pr
  (ite (or (= a pno) (= b pmust)) pno (ite (and (= a pmust) (= b pno)) pmust pmay)))
(define-fun pweak ((a Pr)) Pr (ite (= a pmust) pmay a))
(define-fun inP ((p Pr) (b Bool)) Bool (and (=> (= p pno) (not b)) (=> (= p pmust) b)))
(define-fun n3 ((a Bool) (b Bool) (c Bool)) Int (+ (ite a 1 0) (ite b 1 0) (ite c 1 0)))
"""

HEADS = ["0", "1", "2"]


def decl(name, sort):
    return f"(declare-const {name} {sort})\n"


# ---------------------------------------------------------------------------- L2 model
def l2_abstract(s):
    """declarations for one abstract L2 shape named by suffix `s`"""
    out = decl(f"E{s}", "Pr")
    for h in HEADS:
        out += decl(f"T{s}{h}", "Bool") + decl(f"E{s}{h}", "Pr") + decl(f"Q{s}{h}", "Pr")
    out += decl(f"Olo{s}", "Int") + decl(f"Ohi{s}", "Int")
    out += decl(f"H{s}", "Bool") + decl(f"Eo{s}", "Pr") + decl(f"Qo{s}", "Pr")
    return out


def l2_ok(s):
    """the REPRESENTATION INVARIANTS `Shape.mk` establishes: a consistent `others` interval and a
    MAY-ONLY `otherTail` (mk line `ot0.map(t => weaken(capDepth(t, ...)))`).  The may-only summary is
    load-bearing: channel (d) is read PER UNTRACKED HEAD, and an untracked head of one operand need
    not be present in the other, so a Must in the summary would be attributed to a head whose
    tail-set is empty on that side (z3 produced exactly that countermodel before the invariant was
    added).  Without `mk`'s weakening the union transfer below is UNSOUND."""
    return (f"(and (>= Olo{s} 0) (<= Olo{s} Ohi{s})"
            f" (not (= Eo{s} pmust)) (not (= Qo{s} pmust)))")


def l2_concrete(s):
    out = decl(f"e{s}", "Bool")
    for h in HEADS:
        out += decl(f"p{s}{h}", "Bool") + decl(f"q{s}{h}", "Bool")
    return out


def present(s, h):
    return f"(or p{s}{h} q{s}{h})"


def l2_gamma(a, c):
    """`c ∈ γ(a)` over the four channels of SpatialGamma.gammaShape"""
    tracked = " ".join(
        f"(=> T{a}{h} (and (inP E{a}{h} p{c}{h}) (inP Q{a}{h} q{c}{h})))" for h in HEADS)
    untr = " ".join(f"(and (not T{a}{h}) {present(c, h)})" for h in HEADS)
    cnt = f"(let ((u (n3 {untr}))) (and (<= Olo{a} u) (<= u Ohi{a})))"
    ot = " ".join(
        f"(=> (and (not T{a}{h}) {present(c, h)}) (and (inP Eo{a} p{c}{h}) (inP Qo{a} q{c}{h})))"
        for h in HEADS)
    return f"(and (inP E{a} e{c}) {tracked} {cnt} (=> H{a} (and {ot})))"


def under(a, h, ch):
    """`Shape.under(h)` channel `ch` ∈ {E, Q}: the tracked child, or ∅ when closed, or the WEAKENED
    otherTail summary (never a must claim out of the untracked side)."""
    weak = f"(ite H{a} (pweak {ch}o{a}) pmay)"
    return f"(ite T{a}{h} {ch}{a}{h} (ite (= Ohi{a} 0) pno {weak}))"


def keydiff(x, y):
    """|tracked(y) ∖ tracked(x)| — the discount in the union transfer's others.lo"""
    return "(n3 " + " ".join(f"(and T{y}{h} (not T{x}{h}))" for h in HEADS) + ")"


# ---------------------------------------------------------------------------- L1 model
def l1_abstract(s):
    out = decl(f"E{s}", "Pr")
    for h in HEADS:
        out += decl(f"T{s}{h}", "Bool") + decl(f"C{s}{h}", "Pr")
    out += decl(f"Olo{s}", "Int") + decl(f"Ohi{s}", "Int") + decl(f"H{s}", "Bool") + decl(f"Co{s}", "Pr")
    return out


def l1_concrete(s):
    out = decl(f"e{s}", "Bool")
    for h in HEADS:
        out += decl(f"p{s}{h}", "Bool")
    return out


def l1_gamma(a, c):
    tracked = " ".join(f"(=> T{a}{h} (inP C{a}{h} p{c}{h}))" for h in HEADS)
    untr = " ".join(f"(and (not T{a}{h}) p{c}{h})" for h in HEADS)
    cnt = f"(let ((u (n3 {untr}))) (and (<= Olo{a} u) (<= u Ohi{a})))"
    ot = " ".join(f"(=> (and (not T{a}{h}) p{c}{h}) (inP Co{a} p{c}{h}))" for h in HEADS)
    return f"(and (inP E{a} e{c}) {tracked} {cnt} (=> H{a} (and {ot})))"


def l1_ok(s):
    """the same representation invariants at depth 1 (see l2_ok)"""
    return f"(and (>= Olo{s} 0) (<= Olo{s} Ohi{s}) (not (= Co{s} pmust)))"


def l1_under(a, h):
    weak = f"(ite H{a} (pweak Co{a}) pmay)"
    return f"(ite T{a}{h} C{a}{h} (ite (= Ohi{a} 0) pno {weak}))"


FILES = {}


def emit(name, title, note, body):
    FILES[name] = HDR.format(title=title, note=note) + body + "(check-sat)\n"


# ============================================================================ 1. interval γ/α
emit("gsem_ivl_gamma_adjunction",
     "α/γ ADJUNCTION on the per-class count interval",
     "extensivity (c ∈ γ(α{c})), reductivity (α(γ t) ⊑ t, with equality when t is consistent), and "
     "BOTH directions of the adjunction α S ⊑ t ⟺ S ⊆ γ t for a 3-element S.  This is the Galois "
     "core the class-indexed results below are built from.",
     CNT + """
(declare-const c1 Int) (declare-const c2 Int) (declare-const c3 Int)
(declare-const t Ivl) (declare-const d Ivl)
(define-fun mn3 ((a Int) (b Int) (c Int)) Int (ite (<= a b) (ite (<= a c) a c) (ite (<= b c) b c)))
(define-fun mx3 ((a Int) (b Int) (c Int)) Int (ite (>= a b) (ite (>= a c) a c) (ite (>= b c) b c)))
; α of a 3-element set of counts is the tightest interval containing them
(define-fun alpha3 ((a Int) (b Int) (c Int)) Ivl (mki (fin (mn3 a b c)) (fin (mx3 a b c))))
(define-fun nonneg () Bool (and (>= c1 0) (>= c2 0) (>= c3 0)))
; a CONSISTENT interval with finite endpoints — the shape α ever produces
(define-fun consistent ((i Ivl)) Bool (and (oki i) (not (= (lo i) oo)) (not (= (hi i) oo)) (cle (lo i) (hi i))))
(assert (or
  ; (i) EXTENSIVE
  (and (>= c1 0) (not (inI c1 (alpha3 c1 c1 c1))))
  ; (ii) ADJUNCTION ⇐ : S ⊆ γ t ⇒ α S ⊑ t  (α is the BEST abstraction)
  (and nonneg (oki t) (inI c1 t) (inI c2 t) (inI c3 t) (not (ile (alpha3 c1 c2 c3) t)))
  ; (iii) ADJUNCTION ⇒ : α S ⊑ t ⇒ S ⊆ γ t
  (and nonneg (oki t) (ile (alpha3 c1 c2 c3) t) (not (and (inI c1 t) (inI c2 t) (inI c3 t))))
  ; (iv) REDUCTIVE, and TIGHT: for a consistent finite t, α(γ t) = t (both endpoints are attained)
  (and (consistent d) (not (= (alpha3 (v (lo d)) (v (lo d)) (v (hi d))) d)))))
""")

# ============================================================================ 2. type order
emit("gsem_type_order_containment",
     "the CONCRETIZATION ORDER on the length-indexed type implies γ-CONTAINMENT",
     "`leqt(a,b) ⇒ γ(a) ⊆ γ(b)` for the full SpaceType representation on a 4-length window — both "
     "class endpoints, the SPILL AGGREGATE, and the spill length window.  proofs/spatial/"
     "sp_gamma_order.smt2 proves the one-interval case; this is the class-indexed carrier with the "
     "bucket, which is what SpatialGamma.leq actually decides.",
     CNT + TY + """
(declare-const a Ty) (declare-const b Ty)
(declare-const n0 Int) (declare-const n1 Int) (declare-const n2 Int) (declare-const n3 Int)
(assert (and (okt a) (okt b) (okv n0 n1 n2 n3)
             (leqt a b) (inG a n0 n1 n2 n3) (not (inG b n0 n1 n2 n3))))
""")

# ============================================================================ 3. within gap
emit("gsem_within_not_containment",
     "`SpaceType.within` is NOT γ-containment (upper envelopes only)",
     "GROUND WITNESS.  A = {len0:[0,1], len1:[0,3]}, B = {len0:[0,1], len1:[2,5]}, both with an "
     "empty spill.  `within(A,B)` holds because it compares only upper endpoints, yet the empty "
     "space is in γ(A) and not in γ(B).  The corrected order `leqt` rejects the pair.  This is the "
     "class-indexed restatement of the refutation in proofs/spatial/sp_gamma_order.smt2, and it is "
     "the exact reason `within` licenses only the UPPER half of the Fixpoint post-fixpoint check.",
     CNT + TY + """
(define-fun A () Ty (mkty (mki (fin 0) (fin 1)) (mki (fin 0) (fin 3)) (mki (fin 0) (fin 0)) 0 0))
(define-fun B () Ty (mkty (mki (fin 0) (fin 1)) (mki (fin 2) (fin 5)) (mki (fin 0) (fin 0)) 0 0))
(assert (not (and (okt A) (okt B)
                  (withint A B)              ; the code's check accepts the pair
                  (not (leqt A B))           ; the γ-containment order rejects it
                  (inG A 0 0 0 0)            ; ∅ ∈ γ(A)
                  (not (inG B 0 0 0 0)))))   ; ∅ ∉ γ(B)
""")

# ============================================================================ 4. lub
emit("gsem_type_lub_upper",
     "the LATTICE JOIN of two length-indexed types is an upper bound of both",
     "`γ(a) ∪ γ(b) ⊆ γ(lub(a,b))` for the class-wise interval hull plus the spill/window hull — the "
     "join SpatialGamma.lub implements, and the one `alphaSet` folds with.  Both sides checked.",
     CNT + TY + """
(declare-const a Ty) (declare-const b Ty)
(declare-const n0 Int) (declare-const n1 Int) (declare-const n2 Int) (declare-const n3 Int)
(assert (and (okt a) (okt b) (okv n0 n1 n2 n3)
             (or (inG a n0 n1 n2 n3) (inG b n0 n1 n2 n3))
             (not (inG (lubt a b) n0 n1 n2 n3))))
""")

# ============================================================================ 5. join is not lub
emit("gsem_join_not_lub",
     "`SpatialTypes.join` is the UNION TRANSFER, not the lattice join",
     "GROUND WITNESS.  With A = {len1:[0,0]} and B = {len1:[2,2]}, the code's class-wise rule "
     "(lo = max, hi = saturating +) yields {len1:[2,2]}, which does NOT contain γ(A): the empty "
     "space is in γ(A) and not in γ(join(A,B)).  The interval hull `lubt` does contain it.  "
     "docs/design_spatial_lattice.md §2 calls `join` the lub; it is not one.  The Fixpoint "
     "transfer's use is still coherent (the concrete Fixpoint accumulates a UNION), but the name and "
     "the lattice claim are wrong, and no lub of two spatial types exists in the code.",
     CNT + TY + """
(define-fun A () Ty (mkty (mki (fin 0) (fin 0)) (mki (fin 0) (fin 0)) (mki (fin 0) (fin 0)) 0 0))
(define-fun B () Ty (mkty (mki (fin 0) (fin 0)) (mki (fin 2) (fin 2)) (mki (fin 0) (fin 0)) 0 0))
(assert (not (and (okt A) (okt B)
                  (inG A 0 0 0 0)
                  (not (inG (jointy A B) 0 0 0 0))    ; the code's join is NOT an upper bound
                  (inG (lubt A B) 0 0 0 0))))         ; the interval hull is
""")

# ============================================================================ 6. join sound as union
emit("gsem_join_union_sound",
     "the same class-wise rule IS SOUND as the UNION transfer",
     "From the finite-measure facts about a per-length count of a set union — `max(|A|,|B|) ≤ "
     "|A∪B| ≤ |A|+|B|` and non-negativity, asserted as DEFINITIONAL axioms — the interval "
     "`[max(lo_a,lo_b), hi_a+hi_b]` brackets the union's class count.  Together with "
     "gsem_join_not_lub this pins exactly what `SpatialTypes.join` is: a sound transfer for ∪ and "
     "not an order-theoretic join.",
     CNT + """
(declare-const a Ivl) (declare-const b Ivl)
(declare-const na Int) (declare-const nb Int) (declare-const nu Int)
; DEFINITIONAL: the finite-measure bridge for one length class (cf. proofs/spatial/sp_class_bounds)
; ASSUMED: T7
(assert (>= nu 0))
; ASSUMED: T7
(assert (>= nu na))
; ASSUMED: T7
(assert (>= nu nb))
; ASSUMED: T7
(assert (<= nu (+ na nb)))
(assert (and (oki a) (oki b) (inI na a) (inI nb b) (not (inI nu (ucls a b)))))
""")

# ============================================================================ 7. disjoin
emit("gsem_disjoin_sound",
     "`SpatialTypes.disjoin` (folding a spill-overlapping tracked class into the bucket) preserves γ",
     "The representation invariant is that the spill counts the paths at UNTRACKED lengths.  When "
     "widening leaves a tracked class inside the spill window, `disjoin` folds it in with "
     "lo = max (NOT +, because the two claims may describe the same paths) and hi = +, widening the "
     "window.  Theorem: every concrete vector admitted before the fold is admitted after.  This is "
     "the repair the review credits in its item 1, stated as a γ fact for the first time.",
     CNT + TY + """
(declare-const a Ty)
(declare-const n0 Int) (declare-const n1 Int) (declare-const n2 Int) (declare-const n3 Int)
; BEFORE: classes 0 and 1 tracked, spill covers {2,3} — but its window ALSO covers length 1, which
; is the invariant violation `disjoin` repairs.
(define-fun overlaps ((t Ty)) Bool (and (not (= (hi (rst t)) (fin 0))) (<= (rlo t) 1) (<= 1 (rhi t))))
; AFTER: class 1 is untracked and folded into the bucket; the window is widened to cover it.
(define-fun post ((t Ty)) Ty
  (mkty (c0 t) (mki (fin 0) (fin 0))
        (mki (cmax (lo (rst t)) (lo (c1 t))) (cadd (hi (rst t)) (hi (c1 t))))
        (ite (<= (rlo t) 1) (rlo t) 1) (ite (>= (rhi t) 1) (rhi t) 1)))
; γ AFTER reads class 1 as part of the bucket, so the aggregate is n1+n2+n3
(define-fun inGpost ((t Ty) (n0 Int) (n1 Int) (n2 Int) (n3 Int)) Bool
  (and (inI n0 (c0 t))
       (inI (+ n1 (+ n2 n3)) (rst t))
       (=> (> n1 0) (and (<= (rlo t) 1) (<= 1 (rhi t))))
       (=> (> n2 0) (and (<= (rlo t) 2) (<= 2 (rhi t))))
       (=> (> n3 0) (and (<= (rlo t) 3) (<= 3 (rhi t))))))
(assert (and (okt a) (okv n0 n1 n2 n3) (overlaps a)
             (inG a n0 n1 n2 n3) (not (inGpost (post a) n0 n1 n2 n3))))
""")

# ============================================================================ 8. satisfies weaker
emit("gsem_satisfies_weaker",
     "`SpatialTyping.satisfies` ADMITS values outside γ — the dispatcher gate is not the precondition",
     "GROUND WITNESS.  `satisfies` checks the total size, the class interval of every length PRESENT "
     "in the value, and the length hull.  It never checks that a tracked class with a positive lower "
     "bound has any paths at all, so t = {len1:[1,2], spill{2,3}:[1,2]} accepts a value with two "
     "length-2 paths and no length-1 path, which is not in γ(t).  "
     "`SpecializedRoutine.applicableTo` is built on `satisfies`, so a guarded dispatcher can select "
     "a specialisation for an input violating the precondition it was derived under.",
     CNT + TY + """
(define-fun T () Ty (mkty (mki (fin 0) (fin 0)) (mki (fin 1) (fin 2)) (mki (fin 1) (fin 2)) 2 3))
; SpatialTyping.satisfies, transcribed: total size, the classes PRESENT in v, the length hull
(define-fun szlo ((t Ty)) Cnt (cadd (lo (c0 t)) (cadd (lo (c1 t)) (lo (rst t)))))
(define-fun szhi ((t Ty)) Cnt (cadd (hi (c0 t)) (cadd (hi (c1 t)) (hi (rst t)))))
; `SpaceType.at(l)` for an untracked l inside the window is [0, rest.hi] — not the aggregate
(define-fun atSpill ((t Ty)) Ivl (mki (fin 0) (hi (rst t))))
(define-fun sat ((t Ty) (n0 Int) (n1 Int) (n2 Int) (n3 Int)) Bool
  (let ((tot (+ n0 (+ n1 (+ n2 n3)))))
    (and (cle (szlo t) (fin tot)) (cle (fin tot) (szhi t))
         (=> (> n0 0) (inI n0 (c0 t)))
         (=> (> n1 0) (inI n1 (c1 t)))
         (=> (> n2 0) (and (inI n2 (atSpill t)) (<= (rlo t) 2) (<= 2 (rhi t))))
         (=> (> n3 0) (and (inI n3 (atSpill t)) (<= (rlo t) 3) (<= 3 (rhi t)))))))
(assert (not (and (okt T) (okv 0 0 2 0)
                  (sat T 0 0 2 0)              ; the dispatcher gate accepts it
                  (not (inG T 0 0 2 0)))))     ; γ does not
""")

# ============================================================================ 9. eps rules
emit("gsem_eps_rules",
     "the ε MAY/MUST rules are sound for ∪, ∩, ∖ and for weakening",
     "`Presence.or/and/minus` are the ε transfers of Union/Intersection/Subtraction and `weak` is "
     "what every member-deleting operation applies.  Theorem: if a 3-valued claim is sound for each "
     "operand's ε then the combined claim is sound for the result's ε, in all four cases.  This is "
     "channel (a) of γ, for every binary operator at once.",
     PR + """
(declare-const pa Pr) (declare-const pb Pr) (declare-const ba Bool) (declare-const bb Bool)
(assert (or
  (and (inP pa ba) (inP pb bb) (not (inP (por pa pb) (or ba bb))))
  (and (inP pa ba) (inP pb bb) (not (inP (pand pa pb) (and ba bb))))
  (and (inP pa ba) (inP pb bb) (not (inP (pminus pa pb) (and ba (not bb)))))
  (and (inP pa ba) (not (inP (pweak pa) ba)))))
""")

# ============================================================================ 10. othertail per-head
emit("gsem_othertail_perhead_union",
     "the UNION transfer is not an upper bound of its operands, so an over-cap head summary must be "
     "WEAKENED before folding",
     "GROUND WITNESS.  Channel (d) of γ reads `otherTail` PER UNTRACKED HEAD.  Folding the over-cap "
     "siblings with `Shape.union` therefore attributes one sibling's MUST to all of them: with "
     "pa = Must and pb = No, `por pa pb = Must`, and the empty tail-set admitted by pb is not "
     "admitted by the summary.  This is the root cause of the `Shape.widen` leak this corpus's "
     "executable twin found on 2026-08-07 (SpatialLawCheck's third regression reproducer); the "
     "repair is `weaken` before the fold, and `pweak` restores soundness on the same witness.",
     PR + """
(assert (not (and
  ; the union transfer's ε rule turns No into Must when a sibling forces ε
  (= (por pmust pno) pmust)
  (inP pno false)                       ; the sibling's tail-set is ∅ and pno admits it
  (not (inP (por pmust pno) false))     ; the summary does NOT
  (inP (pweak (por pmust pno)) false))))  ; weakening the summary first restores soundness
""")

# ============================================================================ 11. L2 union
emit("gsem_l2_union_sound",
     "the L2 UNION transfer is γ-sound on all four channels, INCLUDING the others.lo discount",
     "Depth-2 abstract trie, 3 heads, grandchild {x}: the concrete space is a subset of "
     "{ε,0,1,2,0.x,1.x,2.x} so ∪ is EXACT on the cells.  The transfer is the current "
     "`Shape.union`: ε by `or`, tracked children by `or` of `under`, others.hi by +, others.lo by "
     "max of each side DISCOUNTED by the keys the other side newly tracks, otherTail by `or` "
     "per-channel.  Theorem: A ∈ γ(a) ∧ B ∈ γ(b) ⇒ A∪B ∈ γ(a ∪# b).",
     PR + l2_abstract("a") + l2_abstract("b") + l2_concrete("A") + l2_concrete("B") + f"""
; ── the RESULT shape (Shape.union), spelled out channel by channel
(define-fun T0 () Bool (or Ta0 Tb0)) (define-fun T1 () Bool (or Ta1 Tb1)) (define-fun T2 () Bool (or Ta2 Tb2))
(define-fun E () Pr (por Ea Eb))
{''.join(f'(define-fun Eh{h} () Pr (por {under("a", h, "E")} {under("b", h, "E")}))'
         f'(define-fun Qh{h} () Pr (por {under("a", h, "Q")} {under("b", h, "Q")}))' + chr(10)
         for h in HEADS)}
(define-fun closedBoth () Bool (and (= Ohia 0) (= Ohib 0)))
(define-fun loA () Int (let ((d (- Oloa {keydiff("a", "b")}))) (ite (>= d 0) d 0)))
(define-fun loB () Int (let ((d (- Olob {keydiff("b", "a")}))) (ite (>= d 0) d 0)))
(define-fun Olo () Int (ite closedBoth 0 (ite (>= loA loB) loA loB)))
(define-fun Ohi () Int (ite closedBoth 0 (+ Ohia Ohib)))
; the per-head summary: ∅ for a closed side, else its own summary (⊤ = pmay when absent)
(define-fun atE () Pr (ite (= Ohia 0) pno (ite Ha Eoa pmay)))
(define-fun atQ () Pr (ite (= Ohia 0) pno (ite Ha Qoa pmay)))
(define-fun btE () Pr (ite (= Ohib 0) pno (ite Hb Eob pmay)))
(define-fun btQ () Pr (ite (= Ohib 0) pno (ite Hb Qob pmay)))
; `mk` WEAKENS the summary (see l2_ok): without this the transfer is unsound — z3's countermodel
; had b claiming "every untracked head of B has the path h.x" and A contributing an untracked head
; that B does not have at all.
(define-fun Eo () Pr (pweak (por atE btE)))
(define-fun Qo () Pr (pweak (por atQ btQ)))
; ── the CONCRETE union, and γ of the result read off the definitions above
(define-fun eU () Bool (or eA eB))
{''.join(f'(define-fun pU{h} () Bool (or pA{h} pB{h}))(define-fun qU{h} () Bool (or qA{h} qB{h}))' + chr(10)
         for h in HEADS)}
(define-fun presU ((h Int)) Bool false)   ; unused; presence is inlined below
(define-fun gammaU () Bool
  (and (inP E eU)
       {' '.join(f'(=> T{h} (and (inP Eh{h} pU{h}) (inP Qh{h} qU{h})))' for h in HEADS)}
       (let ((u (n3 {' '.join(f'(and (not T{h}) (or pU{h} qU{h}))' for h in HEADS)})))
         (and (<= Olo u) (<= u Ohi)))
       {' '.join(f'(=> (and (not T{h}) (or pU{h} qU{h})) (and (inP Eo pU{h}) (inP Qo qU{h})))' for h in HEADS)}))
(assert (and {l2_ok("a")} {l2_ok("b")} {l2_gamma("a", "A")} {l2_gamma("b", "B")} (not gammaU)))
""")

# ============================================================================ 12. naive max lo unsound
emit("gsem_l2_union_maxlo_unsound",
     "the NAIVE others.lo = max(lo_a, lo_b) in the union transfer is UNSOUND",
     "GROUND WITNESS.  `a` tracks {0,1} and knows at least one UNTRACKED head is present; `b` tracks "
     "{0,1,2} and is closed and empty.  The result tracks {0,1,2}, so the head `a` could not name is "
     "now TRACKED and the untracked count is 0 — but `max(1,0) = 1` demands one.  Discounting by "
     "|keys(b) ∖ keys(a)| = 1 gives 0 and restores soundness on the same witness.  This certifies "
     "the correction carried in the current `Shape.union`.",
     PR + """
; a: tracks heads 0 and 1, ε absent, both tracked children empty, ≥1 untracked head present, ⊤ summary
(define-fun ga () Bool
  (and (inP pno false)                 ; ε ∉ A
       (inP pno false) (inP pno false)  ; head 0 tracked, empty
       (inP pno false) (inP pno false)  ; head 1 tracked, empty
       (= (n3 false false true) 1)))    ; exactly one untracked head (head 2) present in A
; b: tracks 0,1,2, closed, and B = ∅
(define-fun gb () Bool (and (inP pno false) (= (n3 false false false) 0)))
; A ∪ B = A = {2}.  The result tracks 0,1,2 (union of the key sets), so head 2 is TRACKED.
(define-fun uUntracked () Int (n3 false false false))
(define-fun naiveLo () Int 1)          ; max(1, 0)
(define-fun fixedLo () Int 0)          ; relu(1 − |keys(b) ∖ keys(a)|) = relu(1 − 1)
(assert (not (and ga gb
                  (> naiveLo uUntracked)        ; the naive rule rejects the true union
                  (<= fixedLo uUntracked))))    ; the discounted rule admits it
""")

# ============================================================================ 13/14. L2 inter / sub
emit("gsem_l2_inter_sound",
     "the L2 INTERSECTION transfer is γ-sound, closed-head-set rule included",
     "ε by `and` (the only member two sets are both KNOWN to share is a forced ε), tracked children "
     "by `and` of `under`, key set = the intersection when both sides are closed and the closed "
     "side's keys when only one is, others.lo = 0 (a meet DELETES so no must survives the count "
     "channel), others.hi = min, otherTail weakened.  Theorem: A ∈ γ(a) ∧ B ∈ γ(b) ⇒ A∩B ∈ γ(a ∩# b).",
     PR + l2_abstract("a") + l2_abstract("b") + l2_concrete("A") + l2_concrete("B") + f"""
(define-fun closedA () Bool (= Ohia 0))
(define-fun closedB () Bool (= Ohib 0))
; keys: both closed ⇒ intersection; one closed ⇒ that side's keys; neither ⇒ union
{''.join(f'(define-fun T{h} () Bool (ite (and closedA closedB) (and Ta{h} Tb{h})'
         f' (ite closedA Ta{h} (ite closedB Tb{h} (or Ta{h} Tb{h})))))' + chr(10) for h in HEADS)}
(define-fun E () Pr (pand Ea Eb))
{''.join(f'(define-fun Eh{h} () Pr (pand {under("a", h, "E")} {under("b", h, "E")}))'
         f'(define-fun Qh{h} () Pr (pand {under("a", h, "Q")} {under("b", h, "Q")}))' + chr(10)
         for h in HEADS)}
(define-fun Olo () Int 0)
(define-fun Ohi () Int (ite (or closedA closedB) 0 (ite (<= Ohia Ohib) Ohia Ohib)))
(define-fun Eo () Pr (pweak (pand (ite Ha Eoa pmay) (ite Hb Eob pmay))))
(define-fun Qo () Pr (pweak (pand (ite Ha Qoa pmay) (ite Hb Qob pmay))))
(define-fun eU () Bool (and eA eB))
{''.join(f'(define-fun pU{h} () Bool (and pA{h} pB{h}))(define-fun qU{h} () Bool (and qA{h} qB{h}))' + chr(10)
         for h in HEADS)}
(define-fun gammaU () Bool
  (and (inP E eU)
       {' '.join(f'(=> T{h} (and (inP Eh{h} pU{h}) (inP Qh{h} qU{h})))' for h in HEADS)}
       (let ((u (n3 {' '.join(f'(and (not T{h}) (or pU{h} qU{h}))' for h in HEADS)})))
         (and (<= Olo u) (<= u Ohi)))
       {' '.join(f'(=> (and (not T{h}) (or pU{h} qU{h})) (and (inP Eo pU{h}) (inP Qo qU{h})))' for h in HEADS)}))
(assert (and {l2_ok("a")} {l2_ok("b")} {l2_gamma("a", "A")} {l2_gamma("b", "B")} (not gammaU)))
""")

emit("gsem_l2_sub_sound",
     "the L2 SUBTRACTION transfer is γ-sound, including the CLOSED-subtrahend must-count rule",
     "ε by `minus`, children by `minus` of `under`, key set = the minuend's keys, otherTail weakened, "
     "and others.lo = x.others.lo discounted by the number of live heads the CLOSED subtrahend "
     "tracks outside the result's key set (0 when the subtrahend is open).  Theorem: "
     "A ∈ γ(a) ∧ B ∈ γ(b) ⇒ A∖B ∈ γ(a ∖# b).",
     PR + l2_abstract("a") + l2_abstract("b") + l2_concrete("A") + l2_concrete("B") + f"""
{''.join(f'(define-fun T{h} () Bool Ta{h})' + chr(10) for h in HEADS)}
(define-fun E () Pr (pminus Ea Eb))
{''.join(f'(define-fun Eh{h} () Pr (pminus {under("a", h, "E")} {under("b", h, "E")}))'
         f'(define-fun Qh{h} () Pr (pminus {under("a", h, "Q")} {under("b", h, "Q")}))' + chr(10)
         for h in HEADS)}
; a head the CLOSED subtrahend tracks, that is live there and that the result does not track, is the
; only way an untracked head of the minuend can be emptied out
(define-fun liveB ((eh Pr) (qh Pr)) Bool (not (and (= eh pno) (= qh pno))))
(define-fun hit () Int
  (n3 {' '.join(f'(and Tb{h} (liveB Eb{h} Qb{h}) (not T{h}))' for h in HEADS)}))
(define-fun Olo () Int
  (ite (= Ohia 0) 0 (ite (= Ohib 0) (let ((d (- Oloa hit))) (ite (>= d 0) d 0)) 0)))
(define-fun Ohi () Int (ite (= Ohia 0) 0 Ohia))
(define-fun Eo () Pr (ite Ha (pweak Eoa) pmay))
(define-fun Qo () Pr (ite Ha (pweak Qoa) pmay))
(define-fun eU () Bool (and eA (not eB)))
{''.join(f'(define-fun pU{h} () Bool (and pA{h} (not pB{h})))'
         f'(define-fun qU{h} () Bool (and qA{h} (not qB{h})))' + chr(10) for h in HEADS)}
(define-fun gammaU () Bool
  (and (inP E eU)
       {' '.join(f'(=> T{h} (and (inP Eh{h} pU{h}) (inP Qh{h} qU{h})))' for h in HEADS)}
       (let ((u (n3 {' '.join(f'(and (not T{h}) (or pU{h} qU{h}))' for h in HEADS)})))
         (and (<= Olo u) (<= u Ohi)))
       {' '.join(f'(=> (and (not T{h}) (or pU{h} qU{h})) (and (inP Eo pU{h}) (inP Qo qU{h})))' for h in HEADS)}))
(assert (and {l2_ok("a")} {l2_ok("b")} {l2_gamma("a", "A")} {l2_gamma("b", "B")} (not gammaU)))
""")

# ============================================================================ 15. tails union
emit("gsem_l2_tailsunion_sound",
     "the L2 TAILSUNION transfer is γ-sound, and the untracked contribution needs OPEN COUNTS",
     "`TailsUnion` aggregates ACROSS heads, so the per-head reading of channel (d) is exactly wrong "
     "for it: an unknown number of tail-sets each admitted by the summary are unioned, and 'at most "
     "k untracked heads' is not preserved by that.  The transfer therefore folds "
     "`openCounts(otherTail)`.  Theorem, at depth 2 with a single grandchild item: the ε and x cells "
     "of ⋃_h tails(h) are bracketed by `or` over the tracked children and the opened summary.  (The "
     "count channels of the RESULT are not claimed here — that is what `openCounts` gives up.)",
     PR + l2_abstract("a") + l2_concrete("A") + f"""
; the result's two cells: ε ∈ ⋃ tails iff some PRESENT head has the bare path; x ∈ ⋃ tails iff some
; present head has h.x
(define-fun eR () Bool (or pA0 (or pA1 pA2)))
(define-fun qR () Bool (or qA0 (or qA1 qA2)))
; abstract: `or` over the tracked children and (when the head set is open) the summary
(define-fun sumE () Pr (ite (= Ohia 0) pno (ite Ha Eoa pmay)))
(define-fun sumQ () Pr (ite (= Ohia 0) pno (ite Ha Qoa pmay)))
(define-fun ER () Pr (por (por (ite Ta0 Ea0 pno) (por (ite Ta1 Ea1 pno) (ite Ta2 Ea2 pno))) sumE))
(define-fun QR () Pr (por (por (ite Ta0 Qa0 pno) (por (ite Ta1 Qa1 pno) (ite Ta2 Qa2 pno))) sumQ))
(assert (and {l2_ok("a")} {l2_gamma("a", "A")} (not (and (inP ER eR) (inP QR qR)))))
""")

# ============================================================================ 16/17. tails inter
emit("gsem_l2_tailsinter_may_unsound",
     "intersecting the children of MAY-PRESENT heads is UNSOUND for TailsIntersection",
     "GROUND WITNESS.  A shape with a closed head set {0,1}: head 0's child is may-present with no ε "
     "(`E=No`), head 1's child forces ε.  A concrete value where head 0 is ABSENT has "
     "⋂_{present} tails = tails(1) ∋ ε, but `and`-ing both children gives `and(No, Must) = No`, "
     "i.e. 'ε absent'.  An absent head does not participate in the concrete intersection, so the "
     "true result can be strictly LARGER.  This is the witness SpatialLawCheck's second regression "
     "reproducer pins in the code; the repaired rule is certified in "
     "gsem_l2_tailsinter_closed_sound.",
     PR + """
; head 0: may-present, no ε in its tails (E=pno, Q=pmay).  head 1: forces ε (E=pmust, Q=pno).
; concrete: head 0 ABSENT, head 1 present with the bare path.
(define-fun gammaShape () Bool
  (and (inP pno false) (inP pmay false)     ; head 0 tracked, concretely absent — admitted
       (inP pmust true) (inP pno false)))   ; head 1 tracked, present with ε in its tails
(define-fun eR () Bool true)                ; ⋂ over the PRESENT heads = tails(1) ∋ ε
(define-fun buggyE () Pr (pand pno pmust))  ; `and` over every LIVE head = pno
(assert (not (and gammaShape (= buggyE pno) (not (inP buggyE eR)))))
""")

emit("gsem_l2_tailsinter_closed_sound",
     "TailsIntersection IS sound when the participant set is exactly known",
     "The repaired rule: MUST is restored only when the head set is CLOSED and every live head is "
     "MUST-present, so the set of participating heads is exactly the set of live heads.  Theorem at "
     "depth 2 with a single grandchild item: under that guard, `and` over the live children brackets "
     "both cells of ⋂_{present} tails(h).  Modelled with 2 heads (a third adds no case).",
     PR + """
(declare-const E0 Pr) (declare-const Q0 Pr) (declare-const E1 Pr) (declare-const Q1 Pr)
(declare-const p0 Bool) (declare-const q0 Bool) (declare-const p1 Bool) (declare-const q1 Bool)
(define-fun live ((e Pr) (q Pr)) Bool (not (and (= e pno) (= q pno))))
(define-fun mustNE ((e Pr) (q Pr)) Bool (or (= e pmust) (= q pmust)))
; the GUARD: closed head set, and every live head must-present, and at least one live head
(define-fun guard () Bool
  (and (=> (live E0 Q0) (mustNE E0 Q0)) (=> (live E1 Q1) (mustNE E1 Q1))
       (or (live E0 Q0) (live E1 Q1))))
(define-fun g () Bool (and (inP E0 p0) (inP Q0 q0) (inP E1 p1) (inP Q1 q1)))
(define-fun pres0 () Bool (or p0 q0))
(define-fun pres1 () Bool (or p1 q1))
; ⋂ over the PRESENT heads (∅ when none is present, which `guard` excludes)
(define-fun eR () Bool (and (=> pres0 p0) (=> pres1 p1)))
(define-fun qR () Bool (and (=> pres0 q0) (=> pres1 q1)))
; the transfer: `and` over the live children only
(define-fun ER () Pr (ite (and (live E0 Q0) (live E1 Q1)) (pand E0 E1) (ite (live E0 Q0) E0 E1)))
(define-fun QR () Pr (ite (and (live E0 Q0) (live E1 Q1)) (pand Q0 Q1) (ite (live E0 Q0) Q0 Q1)))
(assert (and guard g (not (and (inP ER eR) (inP QR qR)))))
""")

# ============================================================================ 18/19. restriction keys
emit("gsem_l1_restrict_openkeys_unsound",
     "`keys = tracked(x) ∩ tracked(prefixes)` is UNSOUND when x's head set is OPEN",
     "GROUND WITNESS (depth 1).  `x` tracks heads {0,1} and its head set is OPEN, so head 2 may be "
     "present; `prefixes` is CLOSED with the single path `2`.  The true restriction keeps the path "
     "`2`, so head 2 is in the result.  Intersecting only the TRACKED key sets gives ∅ and then "
     "treating the result as closed makes it DEFINITELY EMPTY.  This is the witness SpatialLawCheck's "
     "first regression reproducer pins; the repaired rule takes `keys = tracked(prefixes)` when the "
     "restricted side is open, certified in gsem_l1_restrict_sound.",
     PR + """
; x: ε absent, tracks {0,1} both empty, head set OPEN with exactly one untracked head present
(define-fun gx () Bool (and (inP pno false) (inP pno false) (inP pno false) (= (n3 false false true) 1)))
; prefixes: closed, exactly the path `2`
(define-fun gp () Bool (and (inP pno false) (= (n3 false false true) 1)))
; the restriction keeps the path `2`: head 2 IS present in the result
(define-fun resultHead2 () Bool true)
(define-fun buggyKeys () Int 0)          ; |tracked(x) ∩ tracked(p)| = |{0,1} ∩ {2}| = 0
(define-fun buggyClosed () Bool true)    ; and the result was then treated as closed
(define-fun fixedKeysHas2 () Bool true)  ; the repaired rule takes tracked(p) = {2}
(assert (not (and gx gp resultHead2 (= buggyKeys 0) buggyClosed fixedKeysHas2)))
""")

emit("gsem_l1_restrict_sound",
     "the L1 RESTRICTION transfer is γ-sound with the repaired key rule",
     "Depth 1: each head's tail-set is ∅ or {ε}, so `x <| prefixes` keeps ε iff ε ∈ prefixes, and "
     "keeps the path `h` iff ε ∈ prefixes or `h` ∈ prefixes.  The transfer: ε by `and`; a head "
     "survives only if both sides may have it, with the key set = tracked(prefixes) when x is open "
     "and closed on either side closing the result; others.lo = 0 (a prefix set DELETES); "
     "others.hi = min; otherTail weakened.  Theorem: A ∈ γ(x) ∧ B ∈ γ(p) ⇒ A<|B ∈ γ(x <|# p).  "
     "SCOPE: only the code's GENERAL branch, i.e. `prefixes.eps = No`.  The other branches are "
     "guarded earlier and are separately trivial — a MUST-ε prefix set returns x unchanged, a ⊤ or "
     "head-empty-open prefix set returns weaken(x), and a MAY-ε prefix set returns the union of "
     "weaken(x) with this branch, all sound given this one and the ε rules.  z3 REFUTED the "
     "unguarded version: with ε ∈ B the surviving-head count is bounded by x's untracked count "
     "alone, not by min(x, prefixes) — which is exactly why the code must branch on may-ε first.",
     PR + l1_abstract("x") + l1_abstract("p") + l1_concrete("A") + l1_concrete("B") + f"""
(define-fun closedX () Bool (= Ohix 0))
(define-fun closedP () Bool (= Ohip 0))
{''.join(f'(define-fun T{h} () Bool (ite (and closedX closedP) (and Tx{h} Tp{h})'
         f' (ite closedX Tx{h} (ite closedP Tp{h} (or Tx{h} Tp{h})))))' + chr(10) for h in HEADS)}
(define-fun E () Pr (pand Ex Ep))
; a head survives when x may have it AND (ε ∈ prefixes OR prefixes may have it)
{''.join(f'(define-fun C{h} () Pr (ite (= Ep pmust) {l1_under("x", h)}'
         f' (pand {l1_under("x", h)} (por (pweak Ep) {l1_under("p", h)}))))' + chr(10) for h in HEADS)}
(define-fun Olo () Int 0)
(define-fun Ohi () Int (ite (or closedX closedP) 0 (ite (<= Ohix Ohip) Ohix Ohip)))
(define-fun Co () Pr (ite Hx (pweak Cox) pmay))
; the CONCRETE restriction
(define-fun eR () Bool (and eA eB))
{''.join(f'(define-fun pR{h} () Bool (and pA{h} (or eB pB{h})))' + chr(10) for h in HEADS)}
(define-fun gammaR () Bool
  (and (inP E eR)
       {' '.join(f'(=> T{h} (inP C{h} pR{h}))' for h in HEADS)}
       (let ((u (n3 {' '.join(f'(and (not T{h}) pR{h})' for h in HEADS)})))
         (and (<= Olo u) (<= u Ohi)))
       {' '.join(f'(=> (and (not T{h}) pR{h}) (inP Co pR{h}))' for h in HEADS)}))
(assert (and {l1_ok("x")} {l1_ok("p")} (= Ep pno)
             {l1_gamma("x", "A")} {l1_gamma("p", "B")} (not gammaR)))
""")

# ============================================================================ 20. head counts
emit("gsem_l1_headcount_rules",
     "the HEAD-COUNT bounds for ∪, ∩, ∖ and <| over a 3-head universe",
     "`Shape.headCount` is the group count of an `Iteration`, the fact the length histogram cannot "
     "express at all.  Theorem: the number of DISTINCT heads of A∪B is at most the sum "
     "and at least each side's; of A∩B at most the minimum; of A∖B and A<|B at most A's; and with "
     "CLOSED head sets the union's head set is exactly the union of the two.  Stated on the concrete "
     "sets, which is what the abstract rule has to bracket.",
     PR + """
(declare-const a0 Bool) (declare-const a1 Bool) (declare-const a2 Bool)
(declare-const b0 Bool) (declare-const b1 Bool) (declare-const b2 Bool)
(declare-const eb Bool)
(define-fun HA () Int (n3 a0 a1 a2))
(define-fun HB () Int (n3 b0 b1 b2))
(define-fun HU () Int (n3 (or a0 b0) (or a1 b1) (or a2 b2)))
(define-fun HI () Int (n3 (and a0 b0) (and a1 b1) (and a2 b2)))
(define-fun HS () Int (n3 (and a0 (not b0)) (and a1 (not b1)) (and a2 (not b2))))
; depth-1 restriction: head h survives iff a_h ∧ (ε ∈ B ∨ b_h)
(define-fun HR () Int (n3 (and a0 (or eb b0)) (and a1 (or eb b1)) (and a2 (or eb b2))))
(assert (or
  (> HU (+ HA HB))                                  ; union ≤ sum
  (< HU HA) (< HU HB)                               ; union ≥ each side
  (> HI HA) (> HI HB)                               ; meet ≤ min
  (> HS HA)                                         ; difference ≤ minuend
  (> HR HA)                                         ; restriction ≤ restricted side
  (not (= HU (+ HA (- HB HI))))))                   ; closed sets: |A ∪ B| = |A| + |B| − |A ∩ B|
""")

# ---------------------------------------------------------------------------- registry
REGISTRY = [
    ("α/γ adjunction on a class interval", "gsem_ivl_gamma_adjunction",
     "extensive + reductive + both adjunction directions; the Galois core"),
    ("concretization order ⇒ containment", "gsem_type_order_containment",
     "the class-indexed carrier WITH the spill aggregate — sp_gamma_order does one interval only"),
    ("`within` is not γ-containment", "gsem_within_not_containment",
     "GROUND WITNESS; the exact gap between SpaceType.within and the order"),
    ("lattice join is an upper bound", "gsem_type_lub_upper",
     "γ(a) ∪ γ(b) ⊆ γ(lub a b) — the join SpatialGamma.lub implements"),
    ("`SpatialTypes.join` is NOT the lub", "gsem_join_not_lub",
     "GROUND WITNESS; docs/design_spatial_lattice.md §2 calls it one"),
    ("`SpatialTypes.join` IS the union transfer", "gsem_join_union_sound",
     "proved from the finite-measure bridge (asserted, DEFINITIONAL)"),
    ("`disjoin` preserves γ", "gsem_disjoin_sound",
     "the spill/tracked overlap repair, stated as a γ fact"),
    ("`satisfies` admits non-members", "gsem_satisfies_weaker",
     "GROUND WITNESS; the dispatcher gate is weaker than the precondition"),
    ("ε may/must rules for ∪ ∩ ∖ weaken", "gsem_eps_rules",
     "channel (a) of γ for every binary operator"),
    ("union transfer is not an upper bound", "gsem_othertail_perhead_union",
     "GROUND WITNESS; why an over-cap head summary must be weakened before folding"),
    ("L2 union transfer γ-sound", "gsem_l2_union_sound",
     "all four channels at depth 2, INCLUDING the others.lo key discount"),
    ("naive others.lo = max is unsound", "gsem_l2_union_maxlo_unsound",
     "GROUND WITNESS; certifies the discount in the current Shape.union"),
    ("L2 intersection transfer γ-sound", "gsem_l2_inter_sound", "closed-head-set key rule included"),
    ("L2 subtraction transfer γ-sound", "gsem_l2_sub_sound",
     "including the closed-subtrahend must-count discount"),
    ("L2 tailsUnion transfer γ-sound", "gsem_l2_tailsunion_sound",
     "and why the untracked contribution needs openCounts"),
    ("tailsInter over MAY heads is unsound", "gsem_l2_tailsinter_may_unsound",
     "GROUND WITNESS; an absent head does not participate"),
    ("tailsInter under the closed guard is sound", "gsem_l2_tailsinter_closed_sound",
     "MUST restored exactly when the participant set is known"),
    ("restriction key rule: open ∩ closed", "gsem_l1_restrict_openkeys_unsound",
     "GROUND WITNESS; the corpus wrongly-empty shape"),
    ("L1 restriction transfer γ-sound", "gsem_l1_restrict_sound", "with the repaired key rule"),
    ("head-count bounds ∪ ∩ ∖ <|", "gsem_l1_headcount_rules",
     "the group count of an Iteration — invisible to the histogram"),
]


def main():
    for name, text in FILES.items():
        (outdir / f"{name}.smt2").write_text(text)
    reg = ["law\tkind\tcertificates\tnote"]
    for law, f, note in REGISTRY:
        kind = "DEFINITIONAL" if f == "gsem_join_union_sound" else "FILE"
        reg.append(f"{law}\t{kind}\tspatial-semantic/{f}.smt2\t{note}")
    (outdir / "REGISTRY.tsv").write_text("\n".join(reg) + "\n")
    print(f"wrote {len(FILES)} obligations + REGISTRY.tsv to {outdir}")
    missing = {f for _, f, _ in REGISTRY} ^ set(FILES)
    if missing:
        raise SystemExit(f"REGISTRY and generated files disagree: {missing}")


if __name__ == "__main__":
    main()
