#!/usr/bin/env python3
"""ACCEPTANCE STATUS FROM EVIDENCE: docs/ACCEPTANCE.md cannot be more optimistic than the gates.

Every row of docs/ACCEPTANCE.md is generated from
  - each criterion's title, acceptance sentence and declared dependencies from the development spec;
  - the gates docs/ACCEPTANCE_MAP.tsv names for it, with their recorded results (target/gates.tsv, written by
    `scripts/gates.py --run`);
  - the proof closure it rests on (terminating/REGISTRY.tsv kinds, target/trace-closure.tsv, proofs/spatial/STATUS.tsv);
  - the generated evidence files it names, which must exist and match the committed snapshot.

States, in the order they are decided:
  UNMEASURED              a named gate has no result, or a named evidence file is missing or differs from HEAD
  UNSOUND                 a soundness gate FAILED
  SOUND-BUT-NOT-USEFUL    only usefulness gates FAILED
  CONDITIONAL             every gate passed but a named closure is OPEN or rests on a trusted-base entry
  GREEN                   every gate passed and every named closure is discharged

    python3 scripts/gen_acceptance.py                  write docs/ACCEPTANCE.md and docs/acceptance.tsv
    python3 scripts/gen_acceptance.py --check          fail if the committed docs/ACCEPTANCE.md disagrees with the evidence
    python3 scripts/gen_acceptance.py --inject-open ID treat registry entry ID as OPEN (the acceptance mutation)
    python3 scripts/gen_acceptance.py --simulate-fail NAME   treat gate NAME as FAILED
    python3 scripts/gen_acceptance.py --dirty PATH     treat evidence PATH as differing from HEAD
    python3 scripts/gen_acceptance.py --selftest       the three mutations above each move a row away from GREEN
    python3 scripts/gen_acceptance.py --allow-dirty    do not demote rows whose evidence is uncommitted (a preview, not acceptance)
"""
import hashlib, os, re, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GENERATED_MARK = "<!-- GENERATED by scripts/gen_acceptance.py"


def rows(path):
    out = []
    if not os.path.exists(path):
        return out
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip() or line.startswith("#"):
                continue
            out.append(line.split("\t"))
    return out


def dependency_ids(text):
    """Expand `A1–A3`, `B1, A6` and similar task dependency notation."""
    out = []
    for m in re.finditer(r"([A-E])(\d)(?:\s*[–-]\s*([A-E])?(\d))?", text):
        a, lo, b, hi = m.group(1), int(m.group(2)), m.group(3), m.group(4)
        if hi is None:
            out.append(f"{a}{lo}")
        elif b in (None, a):
            out.extend(f"{a}{n}" for n in range(lo, int(hi) + 1))
        else:
            out.extend((f"{a}{lo}", f"{b}{hi}"))
    return list(dict.fromkeys(out))


def parse_tasks(path):
    """item id -> (title, acceptance sentence, declared dependencies)"""
    items, cur, acc = {}, None, None
    text = open(path, encoding="utf-8").read()
    for line in text.splitlines():
        m = re.match(r"^### ([A-E]\d)\. (.+)$", line)
        if m:
            cur = m.group(1); items[cur] = [m.group(2).strip(), "", []]; acc = None; continue
        if cur is None:
            continue
        if line.startswith("**Acceptance:**"):
            acc = line[len("**Acceptance:**"):].strip(); items[cur][1] = acc; continue
        if line.startswith("**Depends on:**"):
            items[cur][2] = dependency_ids(line[len("**Depends on:**"):])
            acc = None
            continue
        if acc is not None:
            if not line.strip() or line.startswith("**"):
                acc = None
            else:
                items[cur][1] += " " + line.strip()
    return {k: (v[0], v[1], v[2]) for k, v in items.items()}


def git(*args):
    r = subprocess.run(["git", "-C", ROOT] + list(args), capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else None


def snapshot(allow_dirty, forced_dirty):
    porcelain = git("status", "--porcelain") or ""
    changed = set()
    for l in porcelain.splitlines():
        if len(l) > 3:
            changed.add(l[3:].strip().split(" -> ")[-1])
    changed |= set(forced_dirty)

    def dirty(path):
        if allow_dirty and path not in forced_dirty:
            return False
        if not os.path.exists(os.path.join(ROOT, path)):
            return True
        return any(c == path or c.startswith(path.rstrip("/") + "/") for c in changed)
    return bool(porcelain.strip()), dirty


def evidence_identity(amap):
    """A stable identity for acceptance inputs, without an impossible self-referential commit SHA."""
    paths = {
        "tasks.md", "docs/ACCEPTANCE_MAP.tsv", "scripts/gates.py", "scripts/gen_acceptance.py",
        "terminating/REGISTRY.tsv", "proofs/unbounded/REGISTRY.tsv", "proofs/spatial/STATUS.tsv",
        "target/gates.tsv", "target/trace-closure.tsv",
    }
    for c in amap.values():
        if len(c) >= 4 and c[3].strip() != "-":
            paths.update(x.strip() for x in c[3].split(";") if x.strip()
        )
    h = hashlib.sha256()
    for rel in sorted(paths):
        h.update(rel.encode()); h.update(b"\0")
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            h.update(b"<missing>")
        elif rel == "target/gates.tsv":
            # The E3 comparison is pending while it reads this record and PASS after it returns.
            # It is not an input to its own verdict, so exclude it from the stable identity too.
            stable = [c for c in rows(path)
                      if len(c) < 2 or c[1].strip() != "acceptance status agrees with the evidence"]
            h.update("\n".join("\t".join(c) for c in stable).encode())
        elif rel.startswith("target/"):
            h.update("\n".join("\t".join(c) for c in rows(path)).encode())
        elif os.path.isdir(path):
            for base, dirs, files in os.walk(path):
                dirs.sort(); files.sort()
                for name in files:
                    full = os.path.join(base, name)
                    sub = os.path.relpath(full, ROOT)
                    h.update(sub.encode()); h.update(b"\0")
                    with open(full, "rb") as f:
                        h.update(f.read())
        else:
            with open(path, "rb") as f:
                h.update(f.read())
        h.update(b"\0")
    return "sha256:" + h.hexdigest()[:20]


def closure_state(names, injected):
    """names like O6a / traces / spatial -> (state, detail) with state in GREEN | CONDITIONAL"""
    if names == ["-"]:
        return "GREEN", ""
    kinds = {c[0].strip(): c[1].strip() for c in rows(os.path.join(ROOT, "terminating", "REGISTRY.tsv")) + rows(os.path.join(ROOT, "proofs", "unbounded", "REGISTRY.tsv")) if len(c) >= 2}
    opens, conds = [], []
    for n in names:
        if n == "traces":
            tc = rows(os.path.join(ROOT, "target", "trace-closure.tsv"))
            if not tc:
                opens.append("traces: target/trace-closure.tsv missing (run proof_closure.py --check)"); continue
            for c in tc:
                if c[1] == "OPEN":
                    opens.append(f"{c[0]}: OPEN ({c[3] if len(c) > 3 else ''})")
                elif c[1] == "CONDITIONAL":
                    conds.append(f"{c[0]}: {c[3] if len(c) > 3 else 'conditional'}")
            # the injected entries: every trace that unfolds/folds or generalizes rests on them
            for inj in injected:
                if inj in ("O6a", "O12a", "O12b"):
                    opens.append(f"traces: {inj} injected OPEN (every unfold/fold step rests on it)")
        elif n == "spatial":
            for c in rows(os.path.join(ROOT, "proofs", "spatial", "STATUS.tsv")):
                if c and c[-1].strip() == "OPEN":
                    opens.append(f"spatial rule {c[0]}: OPEN")
                elif c and c[-1].strip().startswith("PROVED-MODULO"):
                    conds.append(f"spatial rule {c[0]}: {c[-1].strip()}")
        else:
            if n in injected:
                opens.append(f"{n}: injected OPEN")
            elif not kinds.get(n, "").startswith("MECHANIZED"):
                opens.append(f"{n}: {kinds.get(n, 'not in a registry')}")
    if opens:
        return "CONDITIONAL", "OPEN — " + "; ".join(sorted(set(opens))[:4])
    if conds:
        return "CONDITIONAL", "modulo " + "; ".join(sorted(set(conds))[:3])
    return "GREEN", ""


def compute(allow_dirty=False, injected=(), simulate_fail=(), forced_dirty=(), assume_pass=False):
    items = parse_tasks(os.path.join(ROOT, "tasks.md"))
    amap = {c[0].strip(): c for c in rows(os.path.join(ROOT, "docs", "ACCEPTANCE_MAP.tsv")) if len(c) >= 4}
    results = {}
    if assume_pass:
        # the self-test's synthetic baseline: every named gate PASSED, so a mutation has a GREEN row to move
        for c in amap.values():
            for g in c[1].split("|"):
                if ":" in g:
                    results[g.split(":", 1)[1]] = "PASS"
    for c in rows(os.path.join(ROOT, "target", "gates.tsv")):
        if len(c) >= 3 and not assume_pass:
            results[c[1].strip()] = c[2].strip()
    for name in simulate_fail:
        results[name] = "FAIL"
    tree_dirty, dirty = snapshot(allow_dirty, set(forced_dirty))
    direct = {}
    for item in sorted(items):
        title, sentence, _dependencies = items[item]
        m = amap.get(item)
        if m is None:
            direct[item] = (item, title, sentence, "UNMEASURED", "no row in docs/ACCEPTANCE_MAP.tsv", [], "", [])
            continue
        gates = [g for g in m[1].split("|") if g.strip()]
        closure = [x.strip() for x in m[2].split(";") if x.strip()]
        evidence = [] if m[3].strip() == "-" else [x.strip() for x in m[3].split(";") if x.strip()]
        gate_rows = []
        unmeasured, unsound, notuseful = [], [], []
        for g in gates:
            kind, name = g.split(":", 1)
            st = results.get(name, "NOT-RUN")
            gate_rows.append((kind, name, st))
            if st not in ("PASS", "FAIL"):
                unmeasured.append(name)
            elif st == "FAIL":
                (unsound if kind == "S" else notuseful).append(name)
        dirty_ev = [e for e in evidence if dirty(e)]
        if dirty_ev:
            state, why = "UNMEASURED", "evidence not the committed snapshot: " + ", ".join(dirty_ev)
        elif unmeasured:
            state, why = "UNMEASURED", "no recorded result for: " + ", ".join(unmeasured)
        elif unsound:
            state, why = "UNSOUND", "FAILED: " + ", ".join(unsound)
        elif notuseful:
            state, why = "SOUND-BUT-NOT-USEFUL", "FAILED: " + ", ".join(notuseful)
        else:
            state, why = closure_state(closure or ["-"], set(injected))
        direct[item] = (item, title, sentence, state, why, gate_rows, ";".join(closure), evidence)

    # A task cannot be greener than a task it declares as a prerequisite.  The previous renderer
    # made dependent rows greener than their prerequisites, reversing the declared dependency graph.
    priority = {"GREEN": 0, "CONDITIONAL": 1, "SOUND-BUT-NOT-USEFUL": 2,
                "UNMEASURED": 3, "UNSOUND": 4}
    out, resolved = [], {}
    for item in sorted(items):
        row = direct[item]
        state, why = row[3], row[4]
        deps = items[item][2]
        worse = [(d, resolved[d][3]) for d in deps if d in resolved and priority[resolved[d][3]] > priority[state]]
        if worse:
            level = max(priority[s] for _d, s in worse)
            state = next(s for s, p in priority.items() if p == level)
            names = [f"{d}={s}" for d, s in worse if priority[s] == level]
            why = "dependency not accepted: " + ", ".join(names)
            row = row[:3] + (state, why) + row[5:]
        resolved[item] = row
        out.append(row)
    return evidence_identity(amap), tree_dirty, out


def render(identity, tree_dirty, table, stamp):
    lines = []
    lines.append("# Acceptance status")
    lines.append("")
    lines.append(f"{GENERATED_MARK}; do not edit — `python3 scripts/gen_acceptance.py` regenerates, `--check` fails on drift -->")
    lines.append("")
    lines.append(f"Evidence snapshot `{identity}`. Gate results come from the current `target/gates.tsv` "
                 "(`scripts/gates.py --run`); closures come from `target/trace-closure.tsv` "
                 "(`scripts/proof_closure.py --check`). Repository cleanliness is enforced separately "
                 "by the publication preflight; a dirty listed evidence path makes its row UNMEASURED.")
    lines.append("")
    lines.append("Every row is derived from its acceptance criterion, mapped gates and closures, and the recorded results. States: **GREEN** (every gate passed, every closure discharged), **CONDITIONAL** (gates passed; a named closure is OPEN or rests on a trusted-base entry), **UNSOUND** (a soundness gate failed), **SOUND-BUT-NOT-USEFUL** (only a usefulness gate failed), **UNMEASURED** (a gate has no result or the evidence on disk is not the committed one).")
    lines.append("")
    lines.append("| item | state | why | gates | closure |")
    lines.append("|---|---|---|---|---|")
    for item, title, _sentence, state, why, gate_rows, closure, _ev in table:
        gs = "<br>".join(f"{'✓' if st == 'PASS' else '✗' if st == 'FAIL' else '?'} {name}" for _k, name, st in gate_rows) or "—"
        lines.append(f"| **{item}** {title} | **{state}** | {why or '—'} | {gs} | {closure or '—'} |")
    lines.append("")
    lines.append("## Acceptance sentences")
    lines.append("")
    for item, title, sentence, state, _why, _g, _c, ev in table:
        lines.append(f"### {item}. {title} — {state}")
        lines.append("")
        lines.append(sentence or "_(no acceptance criterion found)_")
        if ev:
            lines.append("")
            lines.append("Evidence: " + ", ".join(f"[`{e}`]({e})" for e in ev))
        lines.append("")
    return "\n".join(lines) + "\n"


def render_tsv(identity, table):
    out = [f"# acceptance data — generated by scripts/gen_acceptance.py; evidence {identity}", "# item\tstate\twhy\tgates\tclosure\tevidence"]
    for item, _title, _s, state, why, gate_rows, closure, ev in table:
        out.append("\t".join([item, state, why, ";".join(f"{k}:{n}={st}" for k, n, st in gate_rows), closure or "-", ";".join(ev) or "-"]))
    return "\n".join(out) + "\n"


def main(argv):
    allow_dirty = "--allow-dirty" in argv
    injected = [argv[i + 1] for i, a in enumerate(argv) if a == "--inject-open"]
    simulate = [argv[i + 1] for i, a in enumerate(argv) if a == "--simulate-fail"]
    forced = [argv[i + 1] for i, a in enumerate(argv) if a == "--dirty"]
    if "--selftest" in argv:
        # the baseline is SYNTHETIC — every gate assumed PASS, evidence assumed committed — so that each
        # mutation has a GREEN (or CONDITIONAL) row to move; the real states come from the real records
        k = dict(allow_dirty=True, assume_pass=True)
        base = {r[0]: r[3] for r in compute(**k)[2]}
        failures = []
        for item in ("C1", "A4", "B3", "D1"):
            if base[item] not in ("GREEN", "CONDITIONAL"):
                failures.append(f"synthetic baseline: {item} is {base[item]}, so no mutation can be shown to move it")
        # 1. deliberately opening a theorem moves C1 (and everything on the trace closure) away from GREEN
        inj = {r[0]: r[3] for r in compute(**k, injected=["O6a"])[2]}
        for item in ("C1", "C4"):
            if inj[item] == "GREEN":
                failures.append(f"injecting O6a open left {item} GREEN")
        # 2. a failed usefulness gate moves a row to SOUND-BUT-NOT-USEFUL, a failed soundness gate to UNSOUND
        sim = {r[0]: r[3] for r in compute(**k, simulate_fail=["morkl.DecisionsCheck"])[2]}
        if sim["B3"] != "SOUND-BUT-NOT-USEFUL":
            failures.append(f"a failed usefulness gate left B3 at {sim['B3']}")
        sim2 = {r[0]: r[3] for r in compute(**k, simulate_fail=["morkl.SpatialCostCheck"])[2]}
        if sim2["A4"] != "UNSOUND":
            failures.append(f"a failed soundness gate left A4 at {sim2['A4']}")
        # 3. a dirtied generated result moves its row to UNMEASURED
        dr = {r[0]: r[3] for r in compute(**k, forced_dirty=["proofs/pipeline/COVERAGE.tsv"])[2]}
        if dr["D1"] != "UNMEASURED":
            failures.append(f"a dirty generated result left D1 at {dr['D1']}")
        for f in failures:
            print(f"  !! {f}")
        print(f"acceptance selftest: {'OK — opening a theorem, failing a gate and dirtying a result each move their row' if not failures else str(len(failures)) + ' failure(s)'}")
        return 1 if failures else 0
    identity, tree_dirty, table = compute(allow_dirty, injected, simulate, forced)
    stamp = ""
    md = render(identity, tree_dirty, table, stamp)
    tsv = render_tsv(identity, table)
    if "--check" in argv:
        committed = os.path.join(ROOT, "docs", "ACCEPTANCE.md")
        if not os.path.exists(committed):
            print("  !! docs/ACCEPTANCE.md is missing"); return 1
        old = open(committed, encoding="utf-8").read()
        if old != md:
            import difflib
            diff = list(difflib.unified_diff(old.splitlines(), md.splitlines(), "committed", "evidence", lineterm="", n=0))
            print("  !! docs/ACCEPTANCE.md disagrees with the evidence:")
            for l in diff[:30]:
                print("     " + l[:200])
            return 1
        print(f"acceptance: docs/ACCEPTANCE.md agrees with the evidence ({sum(1 for r in table if r[3] == 'GREEN')} GREEN of {len(table)})")
        return 0
    with open(os.path.join(ROOT, "docs", "ACCEPTANCE.md"), "w", encoding="utf-8") as f:
        f.write(md)
    with open(os.path.join(ROOT, "docs", "acceptance.tsv"), "w", encoding="utf-8") as f:
        f.write(tsv)
    counts = {}
    for r in table:
        counts[r[3]] = counts.get(r[3], 0) + 1
    print("acceptance: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())) + f"; evidence {identity}{' (dirty tree)' if tree_dirty else ''}")
    for r in table:
        print(f"  {r[0]}  {r[3]:22s} {r[4][:120]}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
