#!/usr/bin/env python3
"""Generate zipper-egg-tests/bridge-prelude.egg from the two source models.

The bridge puts the MOVEMENT SPEC (zipper.egg: sorts B/KL/Z/C/Body over abstract Node) and the
IMPLEMENTATION MODEL (zipper-impl.egg: sorts Tr/CL) into ONE egglog program and adds `Reflect :
Tr -> Z` — a concrete trie reflected as a cursor — so the commuting squares between the two models
are checkable INSIDE the logic (Phase 3 of the certification plan).  Rules are extracted verbatim
from the source files (single source of truth); the impl's `Node` CONSTRUCTOR is renamed `TNode`
(it collides with the movement spec's abstract `Node` SORT).  `RGet`/`RKeys` are INDEPENDENT
lookups (deliberate duplicates of TrUn/child-list walk), so `Sub k (Reflect t) = Reflect (RGet k
t)` is a real commuting square, not a definition unfolding.
"""
import re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
spec = (root / "zipper-spec.egg").read_text()
impl = (root / "zipper-impl.egg").read_text()

def rules_between(text: str, start_marker: str, end_marker: str) -> str:
    """Everything after the datatype block up to the test section."""
    s = text.index(start_marker)
    e = text.index(end_marker)
    return text[s:e]

# movement rules: from the first boolean rule to the 'reusable concrete spaces' section
spec_rules = rules_between(spec, "; ================================================================================================\n; booleans", "; ================================================================================================\n; reusable concrete spaces")
# impl rules: from the boolean section to the 'reusable concrete tries' section
impl_rules = rules_between(impl, "; ---- booleans (the terminal flag algebra) ----", "; ================================================================================================\n; reusable concrete tries")
# drop the impl's boolean rules (shared with the movement spec) and rename its Node constructor
impl_rules = "\n".join(l for l in impl_rules.splitlines()
                       if not re.match(r"\(rewrite \((Or|And|AndNot) ", l.strip()))
impl_rules = impl_rules.replace("(Node ", "(TNode ")

merged_datatypes = """
; ---- abstract concrete-trie node (movement spec's opaque vocabulary) ----
(datatype Node (N i64) (ChildOf Node i64))

(datatype*
  (B (T) (F)
     (Not B) (Or B B) (And B B) (AndNot B B)
     (Eqi i64 i64)
     (TermOf Node) (EmptyOf Node)
     (Term Z) (IsEmpty Z) (IsNilK KL) (TermAt C))
  (KL (KNil) (KCons i64 KL)
      (KeysOf Node) (Keys Z)
      (KMerge KL KL) (KInter KL KL) (KGuard B KL)
      (KFilt KL Z) (KConsIf i64 B KL) (KeysAt C)
      (RKeys CL))
  (Z (Empty) (Eps) (Src Node) (Wrap1 i64 Z)
     (Union Z Z) (Intersection Z Z) (Subtraction Z Z) (Composition Z Z)
     (Restriction Z Z) (Restr Z Z) (Raffination Z Z)
     (TailsUnion Z) (TailsIntersection Z) (Head Z)
     (Unwrap i64 Z) (Iter Z Body) (Guard B Z) (Sub i64 Z)
     (KFoldU KL Z) (KFoldI KL Z) (HFold KL) (IFold KL Z Body) (App Body i64 Z)
     (FocusOf C)
     (Reflect Tr))
  (Body (ConstBody Z) (JoinBody Z) (InvBody) (InvBody2 i64))
  (C (Root Z) (Descend i64 C) (Ascend C))
  (Tr (TNode B CL)
      (TrU Tr Tr) (TrI Tr Tr) (TrS Tr Tr) (TrC Tr Tr)
      (TrR Tr Tr) (TrRaf Tr Tr)
      (TrW i64 Tr) (TrUn i64 Tr)
      (TrTU Tr) (TrTI Tr) (TrH Tr)
      (ClTU CL) (ClTI CL)
      (ZLit Tr) (Mat Tr)
      (RGet i64 Tr))
  (CL (CNil) (CC i64 Tr CL)
      (ClU CL CL) (ClI CL CL) (ClS CL CL) (ClR CL CL) (ClMapC CL Tr)
      (HCl CL)
      (ConsIf i64 Tr CL)))
"""

glue = """
; ================================================================================================
; Reflect : Tr -> Z — a concrete implementation trie viewed as a cursor.  RGet/RKeys are
; INDEPENDENT lookups (not TrUn), so the squares below are real checks, not definition unfoldings.
; ================================================================================================
(rewrite (Term (Reflect (TNode t c))) t)
(rewrite (Sub k (Reflect nd)) (Reflect (RGet k nd)))
(rewrite (RGet k (TNode t (CNil))) (TNode (F) (CNil)))
(rule ((= e (RGet k (TNode t (CC j v r)))) (= k j)) ((union e v)))
(rule ((= e (RGet k (TNode t (CC j v r)))) (< k j)) ((union e (TNode (F) (CNil)))))
(rule ((= e (RGet k (TNode t (CC j v r)))) (< j k)) ((union e (RGet k (TNode t r)))))
(rewrite (Keys (Reflect (TNode t c))) (RKeys c))
(rewrite (RKeys (CNil)) (KNil))
(rewrite (RKeys (CC k v r)) (KCons k (RKeys r)))
(rewrite (IsEmpty (Reflect (TNode (T) c))) (F))
(rewrite (IsEmpty (Reflect (TNode (F) (CNil)))) (T))
(rewrite (IsEmpty (Reflect (TNode (F) (CC k v r)))) (F))
"""

header = """; AUTO-GENERATED by scripts/make_bridge.py from zipper.egg + zipper-impl.egg — do not edit.
; The MOVEMENT SPEC and the IMPLEMENTATION MODEL in one program, bridged by Reflect : Tr -> Z,
; so the commuting squares between spec and implementation are checked INSIDE the logic
; (see zipper-egg-tests/generated/*.egg for the randomized instances).
"""

out = header + merged_datatypes + "\n; ==== movement-spec rules (verbatim from zipper.egg) ====\n" + spec_rules \
    + "\n; ==== implementation rules (verbatim from zipper-impl.egg; Node renamed TNode) ====\n" + impl_rules \
    + glue
(root / "zipper-egg-tests" / "bridge-prelude.egg").write_text(out)
print(f"wrote zipper-egg-tests/bridge-prelude.egg ({len(out.splitlines())} lines)")
